# Generated by Django 6.0 on 2026-02-23 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_rename_address_line_1_branch_address_and_more'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=200)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('owner_phone', models.CharField(blank=True, max_length=20)),
                ('pet_name', models.CharField(max_length=150)),
                ('pet_breed', models.CharField(blank=True, max_length=150)),
                ('pet_history', models.TextField(blank=True, help_text='Optional medical history notes')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('source', models.CharField(choices=[('WALKIN', 'Walk-in (Public)'), ('PORTAL', 'Portal (Logged-in)')], default='WALKIN', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10)),
                ('is_returning_customer', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='branches.branch')),
                ('preferred_vet', models.ForeignKey(blank=True, limit_choices_to={'position': 'VETERINARIAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='employees.staffmember')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
    ]
