# Generated by Django 5.2.7 on 2026-02-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.CharField(choices=[('GENERAL', 'General Consultation'), ('ROUTINE', 'Routine Check-up'), ('VACCINATION', 'Vaccination'), ('SURGERY', 'Surgery'), ('EMERGENCY', 'Emergency'), ('FOLLOW_UP', 'Follow-up')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='symptoms',
            field=models.TextField(blank=True, help_text='Specific symptoms recorded for this visit'),
        ),
    ]
