# Generated by Django 5.2.7 on 2026-02-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_reason_appointment_symptoms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='symptoms',
            new_name='pet_symptoms',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='pet_history',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(choices=[('GENERAL', 'General Consultation'), ('ROUTINE', 'Routine Check-up'), ('VACCINATION', 'Vaccination'), ('SURGERY', 'Surgery'), ('EMERGENCY', 'Emergency'), ('OTHER', 'Other')], default='GENERAL', max_length=20),
        ),
    ]
