# Generated by Django 6.0 on 2026-03-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_rename_symptoms_appointment_pet_symptoms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pet_age',
            field=models.CharField(blank=True, help_text='Age in years', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pet_color',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pet_sex',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pet_species',
            field=models.CharField(blank=True, help_text='e.g. Dog, Cat, Bird', max_length=60),
        ),
    ]
