# Generated by Django 6.0.2 on 2026-03-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_pet_age_appointment_pet_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='owner_address',
            field=models.TextField(blank=True, help_text='Full address of the owner'),
        ),
    ]
