# Generated by Django 6.0.2 on 2026-03-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_owner_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='pet_age',
        ),
        migrations.AddField(
            model_name='appointment',
            name='pet_dob',
            field=models.DateField(blank=True, help_text='Date of birth of the pet', null=True),
        ),
    ]
