# Generated by Django 6.0 on 2026-03-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_remove_appointment_pet_age_appointment_pet_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='pet_dob',
            field=models.CharField(blank=True, help_text='Date of birth or age (e.g., "2020-01-15" or "3 years")', max_length=50, null=True),
        ),
    ]
