# Generated by Django 6.0 on 2026-03-07 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_add_updated_at'),
        ('patients', '0009_alter_pet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pet',
            field=models.ForeignKey(blank=True, help_text='Link to a registered pet profile, if available.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='patients.pet'),
        ),
    ]
