# Generated by Django 6.0 on 2026-03-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_appointment_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='pet_dob',
            field=models.CharField(blank=True, help_text='Date of birth (YYYY-MM-DD)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='source',
            field=models.CharField(choices=[('WALKIN', 'Walk-in (Guest)'), ('PORTAL', 'Portal (Registered User)')], default='WALKIN', max_length=10),
        ),
    ]
