# Generated by Django 6.0 on 2026-03-14 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_appointment_appointment_appoint_c5b816_idx_and_more'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='sale',
            field=models.ForeignKey(blank=True, help_text='Linked sale transaction when appointment is billed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='pos.sale'),
        ),
    ]
