# Generated by Django 6.0.3 on 2026-03-28 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_add_sale_link'),
        ('settings', '0006_clinicalstatus_reasonforvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reason_for_visit',
            field=models.ForeignKey(blank=True, help_text='Reason for the appointment visit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='settings.reasonforvisit'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(blank=True, choices=[('GENERAL', 'General Consultation'), ('ROUTINE', 'Routine Check-up'), ('VACCINATION', 'Vaccination'), ('SURGERY', 'Surgery'), ('EMERGENCY', 'Emergency'), ('OTHER', 'Other')], default='GENERAL', help_text='Legacy reason field - use reason_for_visit instead', max_length=20),
        ),
    ]
