# Generated by Django 6.0.3 on 2026-04-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_appointment_reason_for_visit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='reason',
        ),
    ]
