# Generated by Django 6.0.3 on 2026-05-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_remove_appointment_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='source',
            field=models.CharField(choices=[('WALKIN', 'Walk-In / Guest User'), ('PORTAL', 'Portal Account')], default='WALKIN', max_length=10),
        ),
    ]
