# Generated by Django - RBAC Models Migration
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Migration to add Role-Based Access Control (RBAC) models."""

    dependencies = [
        ('accounts', '0005_activitylog'),
    ]

    operations = [
        # Create Module model
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(
                    choices=[
                        ('dashboard', 'Dashboard'),
                        ('appointments', 'Appointments'),
                        ('patients', 'Patients'),
                        ('medical_records', 'Medical Records'),
                        ('ai_diagnostics', 'AI Diagnostics'),
                        ('pos', 'Point of Sale'),
                        ('clinic_services', 'Clinic Services'),
                        ('soa', 'Statement of Account'),
                        ('payroll', 'Payroll'),
                        ('staff', 'Staff'),
                        ('schedule', 'Schedule'),
                        ('branches', 'Branches'),
                        ('inventory', 'Inventory'),
                        ('stock_monitor', 'Stock Monitor'),
                        ('stock_transfers', 'Stock Transfers'),
                        ('analytics', 'Analytics'),
                        ('notifications', 'Notifications'),
                        ('activity_logs', 'Activity Logs'),
                        ('settings', 'Settings'),
                        ('roles', 'Role Management'),
                    ],
                    max_length=50,
                    unique=True,
                )),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Boxicons class name', max_length=50)),
                ('url_name', models.CharField(blank=True, help_text='Django URL name', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(
                    blank=True,
                    help_text='Parent module for submenu grouping',
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='children',
                    to='accounts.module',
                )),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['display_order', 'name'],
            },
        ),

        # Create SpecialPermission model
        migrations.CreateModel(
            name='SpecialPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Special Permission',
                'verbose_name_plural': 'Special Permissions',
            },
        ),

        # Create Role model
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('hierarchy_level', models.PositiveIntegerField(default=0, help_text='Higher level = more authority (0=basic, 10=admin)')),
                ('is_staff_role', models.BooleanField(default=True, help_text='If True, users with this role access the admin portal')),
                ('is_system_role', models.BooleanField(default=False, help_text='System roles cannot be deleted')),
                ('restrict_to_branch', models.BooleanField(default=True, help_text='If True, users see only their branch data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['-hierarchy_level', 'name'],
            },
        ),

        # Create ModulePermission model (through table)
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(
                    choices=[
                        ('VIEW', 'View'),
                        ('CREATE', 'Create'),
                        ('EDIT', 'Edit'),
                        ('DELETE', 'Delete'),
                        ('APPROVE', 'Approve'),
                        ('EXPORT', 'Export'),
                        ('MANAGE', 'Full Management'),
                    ],
                    default='VIEW',
                    max_length=20,
                )),
                ('module', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='role_permissions',
                    to='accounts.module',
                )),
                ('role', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='module_permissions',
                    to='accounts.role',
                )),
            ],
            options={
                'verbose_name': 'Module Permission',
                'verbose_name_plural': 'Module Permissions',
                'unique_together': {('role', 'module', 'permission_type')},
            },
        ),

        # Create RoleSpecialPermission model
        migrations.CreateModel(
            name='RoleSpecialPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='role_assignments',
                    to='accounts.specialpermission',
                )),
                ('role', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='special_permissions',
                    to='accounts.role',
                )),
            ],
            options={
                'verbose_name': 'Role Special Permission',
                'verbose_name_plural': 'Role Special Permissions',
                'unique_together': {('role', 'permission')},
            },
        ),

        # Add M2M field for Role -> Module through ModulePermission
        migrations.AddField(
            model_name='role',
            name='modules',
            field=models.ManyToManyField(
                related_name='roles',
                through='accounts.ModulePermission',
                to='accounts.module',
            ),
        ),

        # Add assigned_role field to User
        migrations.AddField(
            model_name='user',
            name='assigned_role',
            field=models.ForeignKey(
                blank=True,
                help_text='Custom role with granular permissions',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='users',
                to='accounts.role',
            ),
        ),

        # Update the branch related_name to avoid clash
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(
                blank=True,
                help_text='The branch this user belongs to.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='branch_users',
                to='branches.branch',
            ),
        ),

        # Update role field to add help text
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('PET_OWNER', 'Pet Owner'),
                    ('STAFF', 'Staff'),
                    ('VETERINARIAN', 'Veterinarian'),
                    ('BRANCH_ADMIN', 'Branch Admin'),
                    ('ADMIN', 'Admin'),
                ],
                default='PET_OWNER',
                help_text='Legacy role field - use assigned_role for new RBAC system',
                max_length=20,
            ),
        ),
    ]
