# Generated by Django - Seed default RBAC data
from django.db import migrations


def seed_modules(apps, schema_editor):
    """Create default modules for the system."""
    Module = apps.get_model('accounts', 'Module')

    modules_data = [
        # Main modules
        {'code': 'dashboard', 'name': 'Dashboard', 'icon': 'bx-grid-alt', 'url_name': 'admin_dashboard', 'display_order': 1},
        {'code': 'appointments', 'name': 'Appointments', 'icon': 'bx-calendar-check', 'url_name': 'appointments:admin_list', 'display_order': 2},
        {'code': 'patients', 'name': 'Patients', 'icon': 'bxs-dog', 'url_name': 'patients:admin_list', 'display_order': 3},
        {'code': 'medical_records', 'name': 'Medical Records', 'icon': 'bx-file', 'url_name': 'records:admin_list', 'display_order': 4},
        {'code': 'ai_diagnostics', 'name': 'AI Diagnostics', 'icon': 'bx-brain', 'url_name': '', 'display_order': 5},

        # Finance modules
        {'code': 'pos', 'name': 'Point of Sale', 'icon': 'bx-cart', 'url_name': 'pos:checkout', 'display_order': 10},
        {'code': 'clinic_services', 'name': 'Clinic Services', 'icon': 'bx-briefcase', 'url_name': 'billing:billable_items', 'display_order': 11},
        {'code': 'soa', 'name': 'Statement of Account', 'icon': 'bx-receipt', 'url_name': 'billing:statement_list', 'display_order': 12},
        {'code': 'payroll', 'name': 'Payroll', 'icon': 'bx-money', 'url_name': 'payroll:dashboard', 'display_order': 13},

        # Staff modules
        {'code': 'staff', 'name': 'Staff', 'icon': 'bx-id-card', 'url_name': 'employees:staff_list', 'display_order': 20},
        {'code': 'schedule', 'name': 'Schedule', 'icon': 'bx-calendar-event', 'url_name': 'employees:schedule', 'display_order': 21},
        {'code': 'branches', 'name': 'Branches', 'icon': 'bx-building-house', 'url_name': 'branches:list', 'display_order': 22},
        {'code': 'roles', 'name': 'Role Management', 'icon': 'bx-shield-quarter', 'url_name': 'accounts:role_list', 'display_order': 23},
        {'code': 'inquiries', 'name': 'Inquiries', 'icon': 'bx-envelope', 'url_name': 'inquiries:list', 'display_order': 24},

        # Inventory modules
        {'code': 'inventory', 'name': 'Inventory', 'icon': 'bx-package', 'url_name': 'inventory:management', 'display_order': 30},
        {'code': 'stock_monitor', 'name': 'Stock Monitor', 'icon': 'bx-error-alt', 'url_name': 'inventory:super_admin_stock_monitoring', 'display_order': 31},
        {'code': 'stock_transfers', 'name': 'Stock Transfers', 'icon': 'bx-transfer', 'url_name': 'inventory:transfer_list', 'display_order': 32},

        # Other modules
        {'code': 'analytics', 'name': 'Analytics', 'icon': 'bx-line-chart', 'url_name': 'reports:analytics_dashboard', 'display_order': 40},
        {'code': 'notifications', 'name': 'Notifications', 'icon': 'bx-bell', 'url_name': 'notifications:admin_notifications', 'display_order': 41},
        {'code': 'activity_logs', 'name': 'Activity Logs', 'icon': 'bx-list-check', 'url_name': 'inventory:activity_logs', 'display_order': 42},
        {'code': 'settings', 'name': 'Settings', 'icon': 'bx-cog', 'url_name': 'settings:admin_settings', 'display_order': 50},
    ]

    for data in modules_data:
        Module.objects.get_or_create(code=data['code'], defaults=data)


def seed_special_permissions(apps, schema_editor):
    """Create special permissions."""
    SpecialPermission = apps.get_model('accounts', 'SpecialPermission')

    permissions = [
        # ─── Schedule Management ───────────────────────────────────
        {'code': 'can_manage_own_schedule', 'name': 'Manage Own Schedule', 'description': 'Can view only their own schedule entries and create/edit/delete only their own schedule entries. Cannot view or modify schedules of other staff members.'},
        {'code': 'can_manage_others_schedule', 'name': 'Manage Others Schedule', 'description': 'User can view and manage schedule entries for other staff members'},

        # ─── Payroll ───────────────────────────────────────────────
        {'code': 'can_view_own_payslips', 'name': 'View Own Payslips', 'description': 'User can view their own payslip records'},

        # ─── Inventory & Stock Transfer ────────────────────────────
        {'code': 'can_request_stock_transfer', 'name': 'Request Stock Transfer', 'description': 'User can create stock transfer requests'},

        # ─── Point of Sale ─────────────────────────────────────────
        {'code': 'can_approve_refunds', 'name': 'Approve Refunds', 'description': 'User can approve refund requests'},
        {'code': 'can_void_sales', 'name': 'Void Sales', 'description': 'User can void sales transactions'},
    ]

    for perm in permissions:
        SpecialPermission.objects.get_or_create(code=perm['code'], defaults=perm)


def seed_default_roles(apps, schema_editor):
    """Create default roles with permissions."""
    Role = apps.get_model('accounts', 'Role')
    Module = apps.get_model('accounts', 'Module')
    ModulePermission = apps.get_model('accounts', 'ModulePermission')
    SpecialPermission = apps.get_model('accounts', 'SpecialPermission')
    RoleSpecialPermission = apps.get_model('accounts', 'RoleSpecialPermission')

    def get_module(code):
        try:
            return Module.objects.get(code=code)
        except Module.DoesNotExist:
            return None

    def add_perms(role, module_perms):
        """Add module permissions to a role."""
        for module_code, perm_types in module_perms.items():
            module = get_module(module_code)
            if module:
                for perm_type in perm_types:
                    ModulePermission.objects.get_or_create(
                        role=role,
                        module=module,
                        permission_type=perm_type
                    )

    def add_special_perms(role, perm_codes):
        """Add special permissions to a role."""
        for code in perm_codes:
            try:
                perm = SpecialPermission.objects.get(code=code)
                RoleSpecialPermission.objects.get_or_create(role=role, permission=perm)
            except SpecialPermission.DoesNotExist:
                pass

    # 1. Admin Role (Level 10 - Full Access)
    admin_role, _ = Role.objects.get_or_create(
        code='admin',
        defaults={
            'name': 'Administrator',
            'description': 'Full system access with all permissions',
            'hierarchy_level': 10,
            'is_staff_role': True,
            'is_system_role': True,
            'restrict_to_branch': False,
        }
    )

    # 2. Branch Admin Role (Level 8)
    branch_admin_role, _ = Role.objects.get_or_create(
        code='branch_admin',
        defaults={
            'name': 'Branch Admin',
            'description': 'Full access to branch operations and staff management',
            'hierarchy_level': 8,
            'is_staff_role': True,
            'is_system_role': True,
            'restrict_to_branch': True,
        }
    )
    add_perms(branch_admin_role, {
        'dashboard': ['VIEW', 'MANAGE'],
        'appointments': ['VIEW', 'CREATE', 'EDIT', 'DELETE', 'MANAGE'],
        'patients': ['VIEW', 'CREATE', 'EDIT', 'DELETE'],
        'medical_records': ['VIEW', 'CREATE', 'EDIT', 'DELETE'],
        'ai_diagnostics': ['VIEW', 'CREATE'],
        'pos': ['VIEW', 'CREATE', 'EDIT', 'DELETE', 'MANAGE'],
        'clinic_services': ['VIEW', 'CREATE', 'EDIT'],
        'soa': ['VIEW', 'CREATE', 'EDIT', 'DELETE'],
        'payroll': ['VIEW'],
        'staff': ['VIEW', 'CREATE', 'EDIT'],
        'schedule': ['VIEW', 'CREATE', 'EDIT', 'DELETE', 'MANAGE'],
        'inventory': ['VIEW', 'CREATE', 'EDIT', 'DELETE'],
        'stock_monitor': ['VIEW'],
        'stock_transfers': ['VIEW', 'CREATE', 'EDIT', 'APPROVE'],
        'analytics': ['VIEW'],
        'notifications': ['VIEW', 'MANAGE'],
        'activity_logs': ['VIEW'],
    })
    add_special_perms(branch_admin_role, [
        'can_view_own_payslips', 'can_manage_others_schedule', 'can_approve_refunds', 'can_void_sales'
    ])

    # 3. Veterinarian Role (Level 5)
    vet_role, _ = Role.objects.get_or_create(
        code='veterinarian',
        defaults={
            'name': 'Veterinarian',
            'description': 'Medical staff with patient and record management',
            'hierarchy_level': 5,
            'is_staff_role': True,
            'is_system_role': True,
            'restrict_to_branch': True,
        }
    )
    add_perms(vet_role, {
        'dashboard': ['VIEW'],
        'appointments': ['VIEW', 'EDIT'],  # Read/Confirm only
        'patients': ['VIEW', 'CREATE', 'EDIT'],
        'medical_records': ['VIEW', 'CREATE', 'EDIT'],
        'ai_diagnostics': ['VIEW', 'CREATE'],
        'schedule': ['VIEW', 'CREATE', 'EDIT', 'DELETE'],  # Own schedule CRUD
        'notifications': ['VIEW'],
    })
    add_special_perms(vet_role, [
        'can_view_own_payslips', 'can_manage_own_schedule'
    ])

    # 4. Receptionist Role (Level 4)
    receptionist_role, _ = Role.objects.get_or_create(
        code='receptionist',
        defaults={
            'name': 'Receptionist',
            'description': 'Front desk operations including appointments and POS',
            'hierarchy_level': 4,
            'is_staff_role': True,
            'is_system_role': True,
            'restrict_to_branch': True,
        }
    )
    add_perms(receptionist_role, {
        'dashboard': ['VIEW'],
        'appointments': ['VIEW', 'CREATE', 'EDIT', 'DELETE'],
        'patients': ['VIEW', 'CREATE', 'EDIT'],
        'pos': ['VIEW', 'CREATE', 'EDIT'],
        'clinic_services': ['VIEW'],
        'soa': ['VIEW', 'CREATE', 'EDIT'],
        'inventory': ['VIEW'],
        'stock_transfers': ['VIEW', 'CREATE'],  # Can request transfers
        'notifications': ['VIEW'],
    })
    add_special_perms(receptionist_role, [
        'can_view_own_payslips', 'can_request_stock_transfer'
    ])

    # 5. Cashier Role (Level 4)
    cashier_role, _ = Role.objects.get_or_create(
        code='cashier',
        defaults={
            'name': 'Cashier',
            'description': 'Point of Sale and payment processing',
            'hierarchy_level': 4,
            'is_staff_role': True,
            'is_system_role': True,
            'restrict_to_branch': True,
        }
    )
    add_perms(cashier_role, {
        'dashboard': ['VIEW'],
        'pos': ['VIEW', 'CREATE', 'EDIT', 'DELETE', 'MANAGE'],
        'clinic_services': ['VIEW'],
        'soa': ['VIEW', 'CREATE'],
        'inventory': ['VIEW'],
        'notifications': ['VIEW'],
    })
    add_special_perms(cashier_role, ['can_view_own_payslips'])

    # 6. Vet Assistant Role (Level 2)
    vet_assistant_role, _ = Role.objects.get_or_create(
        code='vet_assistant',
        defaults={
            'name': 'Vet Assistant',
            'description': 'Support role with read-only access to medical data',
            'hierarchy_level': 2,
            'is_staff_role': True,
            'is_system_role': True,
            'restrict_to_branch': True,
        }
    )
    add_perms(vet_assistant_role, {
        'dashboard': ['VIEW'],
        'appointments': ['VIEW'],  # Read-only
        'patients': ['VIEW'],  # Read-only
        'medical_records': ['VIEW'],  # Read-only
        'inventory': ['VIEW'],
        'notifications': ['VIEW'],
    })
    add_special_perms(vet_assistant_role, ['can_view_own_payslips'])


def reverse_seed(apps, schema_editor):
    """Reverse the seeding - delete all seeded data."""
    Role = apps.get_model('accounts', 'Role')
    Module = apps.get_model('accounts', 'Module')
    SpecialPermission = apps.get_model('accounts', 'SpecialPermission')

    # Delete roles (will cascade to ModulePermission and RoleSpecialPermission)
    Role.objects.filter(is_system_role=True).delete()

    # Delete modules
    Module.objects.all().delete()

    # Delete special permissions
    SpecialPermission.objects.all().delete()


class Migration(migrations.Migration):
    """Data migration to seed default RBAC data."""

    dependencies = [
        ('accounts', '0006_rbac_models'),
    ]

    operations = [
        migrations.RunPython(seed_modules, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(seed_special_permissions, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(seed_default_roles, reverse_code=reverse_seed),
    ]
