# Generated by Django 6.0.3 on 2026-03-18 13:53

from django.db import migrations


def map_legacy_roles(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    Role = apps.get_model('accounts', 'Role')
    
    # Map old string role choices to new Role codes
    role_mapping = {
        'ADMIN': 'admin',
        'BRANCH_ADMIN': 'branch_admin',
        'VETERINARIAN': 'veterinarian',
        'STAFF': 'staff',  # We'll map generic staff to receptionist as a safe fallback
    }
    
    for old_role, new_code in role_mapping.items():
        try:
            role_obj = Role.objects.get(code=new_code)
            User.objects.filter(role=old_role).update(assigned_role=role_obj)
        except Role.DoesNotExist:
            print(f"\nWarning: Role code '{new_code}' not found. Cannot map users with old role '{old_role}'.")

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_seed_rbac_data'),
    ]

    operations = [
        migrations.RunPython(map_legacy_roles, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
