# Generated by Django - Add missing modules and User role
from django.db import migrations


def add_missing_modules(apps, schema_editor):
    """Add missing modules to the system."""
    Module = apps.get_model('accounts', 'Module')

    missing_modules = [
        {
            'code': 'user_portal',
            'name': 'User Portal',
            'description': 'Pet owner dashboard and features',
            'icon': 'bx-user',
            'url_name': 'user_dashboard',
            'display_order': 0,
        },
        {
            'code': 'admin_dashboard',
            'name': 'Admin Dashboard',
            'description': 'Staff administrative dashboard',
            'icon': 'bx-grid-alt',
            'url_name': 'admin_dashboard',
            'display_order': 1,
        },
        {
            'code': 'reports',
            'name': 'Reports',
            'description': 'System reports and analytics',
            'icon': 'bx-bar-chart-alt-2',
            'url_name': 'reports:report_index',
            'display_order': 45,
        },
    ]

    for data in missing_modules:
        Module.objects.get_or_create(code=data['code'], defaults=data)


def add_user_role(apps, schema_editor):
    """Add the User (pet owner) role."""
    Role = apps.get_model('accounts', 'Role')
    Module = apps.get_model('accounts', 'Module')
    ModulePermission = apps.get_model('accounts', 'ModulePermission')

    # Create User role for pet owners
    user_role, created = Role.objects.get_or_create(
        code='user',
        defaults={
            'name': 'User',
            'description': 'Pet owner / customer with portal access',
            'hierarchy_level': 0,
            'is_staff_role': False,  # Not staff - uses user portal
            'is_system_role': True,
            'restrict_to_branch': False,  # Not applicable
        }
    )

    if created:
        # Add basic permissions for user portal
        try:
            user_portal = Module.objects.get(code='user_portal')
            ModulePermission.objects.get_or_create(
                role=user_role,
                module=user_portal,
                permission_type='VIEW'
            )
        except Module.DoesNotExist:
            pass

        try:
            appointments = Module.objects.get(code='appointments')
            ModulePermission.objects.get_or_create(
                role=user_role,
                module=appointments,
                permission_type='VIEW'
            )
            ModulePermission.objects.get_or_create(
                role=user_role,
                module=appointments,
                permission_type='CREATE'
            )
        except Module.DoesNotExist:
            pass

        try:
            patients = Module.objects.get(code='patients')
            ModulePermission.objects.get_or_create(
                role=user_role,
                module=patients,
                permission_type='VIEW'
            )
        except Module.DoesNotExist:
            pass


def reverse_migration(apps, schema_editor):
    """Reverse: remove added modules and user role."""
    Module = apps.get_model('accounts', 'Module')
    Role = apps.get_model('accounts', 'Role')

    Module.objects.filter(code__in=['user_portal', 'admin_dashboard', 'reports']).delete()
    Role.objects.filter(code='user').delete()


class Migration(migrations.Migration):
    """Add missing modules and User role."""

    dependencies = [
        ('accounts', '0008_remove_user_role'),
    ]

    operations = [
        migrations.RunPython(add_missing_modules, reverse_code=reverse_migration),
        migrations.RunPython(add_user_role, reverse_code=migrations.RunPython.noop),
    ]
