# Generated by Django - Update roles and hierarchy
from django.db import migrations


def update_roles_hierarchy(apps, schema_editor):
    """
    Update roles to match the new hierarchy structure:
    - Rename 'admin' to 'superadmin'
    - Update Veterinarian hierarchy from 5 to 6
    - Migrate Cashier users to Receptionist
    - Delete Cashier role
    """
    Role = apps.get_model('accounts', 'Role')
    User = apps.get_model('accounts', 'User')
    ModulePermission = apps.get_model('accounts', 'ModulePermission')
    RoleSpecialPermission = apps.get_model('accounts', 'RoleSpecialPermission')

    # 1. Rename 'admin' role to 'superadmin'
    try:
        admin_role = Role.objects.get(code='admin')
        admin_role.code = 'superadmin'
        admin_role.name = 'Superadmin'
        admin_role.description = 'Full system access with all permissions'
        admin_role.save()
    except Role.DoesNotExist:
        pass

    # 2. Update Veterinarian hierarchy from 5 to 6
    try:
        vet_role = Role.objects.get(code='veterinarian')
        vet_role.hierarchy_level = 6
        vet_role.save()
    except Role.DoesNotExist:
        pass

    # 3. Migrate Cashier users to Receptionist and delete Cashier role
    try:
        cashier_role = Role.objects.get(code='cashier')
        receptionist_role = Role.objects.get(code='receptionist')

        # Move any users from Cashier to Receptionist
        User.objects.filter(assigned_role=cashier_role).update(assigned_role=receptionist_role)

        # Copy any unique module permissions from Cashier to Receptionist
        cashier_perms = ModulePermission.objects.filter(role=cashier_role)
        for perm in cashier_perms:
            ModulePermission.objects.get_or_create(
                role=receptionist_role,
                module=perm.module,
                permission_type=perm.permission_type
            )

        # Copy any unique special permissions from Cashier to Receptionist
        cashier_special_perms = RoleSpecialPermission.objects.filter(role=cashier_role)
        for sp in cashier_special_perms:
            RoleSpecialPermission.objects.get_or_create(
                role=receptionist_role,
                permission=sp.permission
            )

        # Now delete the Cashier role (will cascade delete its permissions)
        cashier_role.delete()

    except Role.DoesNotExist:
        pass


def reverse_roles_update(apps, schema_editor):
    """Reverse: restore original role structure."""
    Role = apps.get_model('accounts', 'Role')
    Module = apps.get_model('accounts', 'Module')
    ModulePermission = apps.get_model('accounts', 'ModulePermission')
    SpecialPermission = apps.get_model('accounts', 'SpecialPermission')
    RoleSpecialPermission = apps.get_model('accounts', 'RoleSpecialPermission')

    # 1. Rename 'superadmin' back to 'admin'
    try:
        superadmin_role = Role.objects.get(code='superadmin')
        superadmin_role.code = 'admin'
        superadmin_role.name = 'Administrator'
        superadmin_role.save()
    except Role.DoesNotExist:
        pass

    # 2. Restore Veterinarian hierarchy to 5
    try:
        vet_role = Role.objects.get(code='veterinarian')
        vet_role.hierarchy_level = 5
        vet_role.save()
    except Role.DoesNotExist:
        pass

    # 3. Recreate Cashier role
    cashier_role, created = Role.objects.get_or_create(
        code='cashier',
        defaults={
            'name': 'Cashier',
            'description': 'Point of Sale and payment processing',
            'hierarchy_level': 4,
            'is_staff_role': True,
            'is_system_role': True,
            'restrict_to_branch': True,
        }
    )

    if created:
        # Add basic cashier permissions
        def get_module(code):
            try:
                return Module.objects.get(code=code)
            except Module.DoesNotExist:
                return None

        cashier_perms = {
            'dashboard': ['VIEW'],
            'pos': ['VIEW', 'CREATE', 'EDIT', 'DELETE', 'MANAGE'],
            'clinic_services': ['VIEW'],
            'soa': ['VIEW', 'CREATE'],
            'inventory': ['VIEW'],
            'notifications': ['VIEW'],
        }

        for module_code, perm_types in cashier_perms.items():
            module = get_module(module_code)
            if module:
                for perm_type in perm_types:
                    ModulePermission.objects.get_or_create(
                        role=cashier_role,
                        module=module,
                        permission_type=perm_type
                    )

        # Add special permission
        try:
            perm = SpecialPermission.objects.get(code='can_view_own_payslips')
            RoleSpecialPermission.objects.get_or_create(role=cashier_role, permission=perm)
        except SpecialPermission.DoesNotExist:
            pass


class Migration(migrations.Migration):
    """Update roles and hierarchy structure."""

    dependencies = [
        ('accounts', '0009_add_missing_modules_and_user_role'),
    ]

    operations = [
        migrations.RunPython(update_roles_hierarchy, reverse_code=reverse_roles_update),
    ]
