# Generated by Django 6.0.3 on 2026-03-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_update_roles_hierarchy'),
        ('branches', '0004_branch_badge_label_branch_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('EXPORT', 'Export'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='object_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='category',
            field=models.CharField(choices=[('STOCK', 'Stock Management'), ('USER', 'User Management'), ('SYSTEM', 'System Settings'), ('APPOINTMENT', 'Appointment'), ('MEDICAL', 'Medical Records'), ('BILLING', 'Billing'), ('POS', 'Point of Sale'), ('PATIENT', 'Patient'), ('PAYROLL', 'Payroll'), ('STAFF', 'Staff')], default='SYSTEM', max_length=50),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['category', '-timestamp'], name='accounts_ac_categor_df1b03_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-timestamp'], name='accounts_ac_user_id_9bf4ca_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action_type', '-timestamp'], name='accounts_ac_action__c0f54c_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['branch', '-timestamp'], name='accounts_ac_branch__ff4713_idx'),
        ),
    ]
