# Generated by Django 6.0.3 on 2026-04-04 12:19

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_activitylog_action_type_activitylog_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Supported formats: .png, .jpeg (Max 10MB)', null=True, upload_to='profiles/', validators=[utils.validators.validate_image_file]),
        ),
    ]
