# Generated by Django 6.0.3 on 2026-04-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='restrict_to_branch',
        ),
        migrations.AddField(
            model_name='modulepermission',
            name='restrict_to_branch',
            field=models.BooleanField(default=False, help_text='If True, users see only their branch data for this module'),
        ),
        migrations.AlterField(
            model_name='modulepermission',
            name='permission_type',
            field=models.CharField(choices=[('VIEW', 'View'), ('CREATE', 'Create'), ('EDIT', 'Edit'), ('DELETE', 'Delete'), ('MANAGE', 'Full Management')], default='VIEW', max_length=20),
        ),
    ]
