# Generated by Django 6.0.3 on 2026-04-10 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_backfill_staff_notifications_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_contact_name', models.CharField(blank=True, help_text='Emergency contact person name', max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, help_text='Emergency contact phone number', max_length=20)),
                ('preferred_communication', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PHONE', 'Phone Call')], default='EMAIL', help_text='Preferred method of communication', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this pet owner (visible to staff only)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Linked user account', on_delete=django.db.models.deletion.CASCADE, related_name='pet_owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pet Owner Profile',
                'verbose_name_plural': 'Pet Owner Profiles',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='OTPToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(help_text='6-digit OTP code', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Token',
                'verbose_name_plural': 'OTP Tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_ot_user_id_a1d80f_idx'), models.Index(fields=['otp_code', 'is_used'], name='accounts_ot_otp_cod_858793_idx')],
            },
        ),
    ]
