# Generated by Django 6.0.3 on 2026-04-28 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_add_reservations_module'),
        ('accounts', '0023_alter_module_code'),
    ]

    operations = [
    ]
