# Generated by Django 6.0.3 on 2026-04-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_merge_20260428_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('appointments', 'Appointments'), ('patients', 'Patients'), ('medical_records', 'Medical Records'), ('ai_diagnostics', 'AI Diagnostics'), ('pos', 'Point of Sale'), ('clinic_services', 'Clinic Services'), ('soa', 'Statement of Account'), ('payroll', 'Payroll'), ('staff', 'Staff'), ('schedule', 'Schedule'), ('branches', 'Branches'), ('inquiries', 'Inquiries'), ('inventory', 'Inventory'), ('reservations', 'Reservations'), ('stock_monitor', 'Stock Monitor'), ('stock_transfers', 'Stock Transfers'), ('analytics', 'Analytics'), ('notifications', 'Notifications'), ('activity_logs', 'Activity Logs'), ('settings', 'Settings'), ('roles', 'Role Management')], max_length=50, unique=True),
        ),
    ]
