# Generated by Django - Remove legacy can_manage_reservations special permission
from django.db import migrations


def remove_can_manage_reservations_permission(apps, schema_editor):
    """Remove the legacy can_manage_reservations special permission."""
    SpecialPermission = apps.get_model('accounts', 'SpecialPermission')
    SpecialPermission.objects.filter(code='can_manage_reservations').delete()


def restore_can_manage_reservations_permission(apps, schema_editor):
    """Restore the can_manage_reservations special permission on rollback."""
    SpecialPermission = apps.get_model('accounts', 'SpecialPermission')
    SpecialPermission.objects.get_or_create(
        code='can_manage_reservations',
        defaults={
            'name': 'Can manage reservations',
            'description': 'Allow managing product reservations without full inventory access'
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_module_code'),
    ]

    operations = [
        migrations.RunPython(
            remove_can_manage_reservations_permission,
            reverse_code=restore_can_manage_reservations_permission
        ),
    ]
