# Generated by Django - move Reservations below Inventory Management
from django.db import migrations


def move_reservations_below_inventory(apps, schema_editor):
    """Place Reservations after Inventory in module ordering."""
    Module = apps.get_model('accounts', 'Module')
    Module.objects.filter(code='reservations').update(display_order=31)


def restore_reservations_order(apps, schema_editor):
    """Restore the previous Reservations ordering on rollback."""
    Module = apps.get_model('accounts', 'Module')
    Module.objects.filter(code='reservations').update(display_order=20)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_legacy_reservations_special_permission'),
    ]

    operations = [
        migrations.RunPython(move_reservations_below_inventory, reverse_code=restore_reservations_order),
    ]
