# Generated by Django - Add manage others schedule special permission
from django.db import migrations


def add_manage_others_schedule_permission(apps, schema_editor):
    """Create the manage others schedule special permission and assign it to branch admin roles."""
    SpecialPermission = apps.get_model('accounts', 'SpecialPermission')
    Role = apps.get_model('accounts', 'Role')
    RoleSpecialPermission = apps.get_model('accounts', 'RoleSpecialPermission')

    permission, _ = SpecialPermission.objects.get_or_create(
        code='can_manage_others_schedule',
        defaults={
            'name': 'Manage Others Schedule',
            'description': 'User can view and manage schedule entries for other staff members',
        },
    )

    if permission.name != 'Manage Others Schedule' or permission.description != 'User can view and manage schedule entries for other staff members':
        permission.name = 'Manage Others Schedule'
        permission.description = 'User can view and manage schedule entries for other staff members'
        permission.save(update_fields=['name', 'description'])

    for role_code in ['branch_admin', 'admin', 'superadmin']:
        try:
            role = Role.objects.get(code=role_code)
        except Role.DoesNotExist:
            continue

        RoleSpecialPermission.objects.get_or_create(role=role, permission=permission)


def remove_manage_others_schedule_permission(apps, schema_editor):
    """Remove the manage others schedule special permission."""
    SpecialPermission = apps.get_model('accounts', 'SpecialPermission')
    RoleSpecialPermission = apps.get_model('accounts', 'RoleSpecialPermission')

    try:
        permission = SpecialPermission.objects.get(code='can_manage_others_schedule')
    except SpecialPermission.DoesNotExist:
        return

    RoleSpecialPermission.objects.filter(permission=permission).delete()
    permission.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0027_move_reservations_below_inventory'),
    ]

    operations = [
        migrations.RunPython(add_manage_others_schedule_permission, reverse_code=remove_manage_others_schedule_permission),
    ]
