# Generated by Django - update Manage Own Schedule special permission wording
from django.db import migrations


def update_manage_own_schedule_permission(apps, schema_editor):
    """Update the Manage Own Schedule permission description."""
    SpecialPermission = apps.get_model('accounts', 'SpecialPermission')

    description = (
        'Can view only their own schedule entries and create/edit/delete only their own schedule entries. '
        'Cannot view or modify schedules of other staff members.'
    )

    try:
        permission = SpecialPermission.objects.get(code='can_manage_own_schedule')
    except SpecialPermission.DoesNotExist:
        SpecialPermission.objects.create(
            code='can_manage_own_schedule',
            name='Manage Own Schedule',
            description=description,
        )
        return

    updates = []
    if permission.name != 'Manage Own Schedule':
        permission.name = 'Manage Own Schedule'
        updates.append('name')
    if permission.description != description:
        permission.description = description
        updates.append('description')

    if updates:
        permission.save(update_fields=updates)


def reverse_manage_own_schedule_permission(apps, schema_editor):
    """Restore the previous Manage Own Schedule wording."""
    SpecialPermission = apps.get_model('accounts', 'SpecialPermission')

    try:
        permission = SpecialPermission.objects.get(code='can_manage_own_schedule')
    except SpecialPermission.DoesNotExist:
        return

    permission.description = (
        'Can view schedules in own branch and create/edit/delete only their own schedule entries. '
        'Cannot modify schedules of other staff members.'
    )
    permission.save(update_fields=['description'])


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0029_remove_view_own_payslips'),
    ]

    operations = [
        migrations.RunPython(update_manage_own_schedule_permission, reverse_manage_own_schedule_permission),
    ]