# Generated by Django - Reorganize module display order for role form
from django.db import migrations


def reorganize_module_display_order(apps, schema_editor):
    """Reorganize module display order according to the new format:
    Patients, Appointments, Medical Records, AI Diagnostics, 
    Inquiries, Clinic Services, Inventory Management, Reservations
    """
    Module = apps.get_model('accounts', 'Module')
    
    new_order = {
        'patients': 10,
        'appointments': 11,
        'medical_records': 12,
        'ai_diagnostics': 13,
        'inquiries': 14,
        'clinic_services': 15,
        'inventory': 16,
        'reservations': 17,
    }
    
    for code, display_order in new_order.items():
        Module.objects.filter(code=code).update(display_order=display_order)


def restore_module_display_order(apps, schema_editor):
    """Restore the previous module display order."""
    Module = apps.get_model('accounts', 'Module')
    
    previous_order = {
        'appointments': 2,
        'patients': 3,
        'medical_records': 4,
        'ai_diagnostics': 5,
        'clinic_services': 11,
        'inventory': 30,
        'inquiries': 24,
        'reservations': 31,
    }
    
    for code, display_order in previous_order.items():
        Module.objects.filter(code=code).update(display_order=display_order)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_update_manage_own_schedule_permission'),
    ]

    operations = [
        migrations.RunPython(reorganize_module_display_order, reverse_code=restore_module_display_order),
    ]
