"""
Django settings for FMHANIMALCLINIC project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import warnings
from pathlib import Path


def _load_environment_file(env_path):
    """Load key/value pairs from a .env file into os.environ without overriding existing values."""
    if not env_path.exists():
        return

    with open(env_path, encoding='utf-8') as handle:
        for raw_line in handle:
            line = raw_line.strip()
            if not line or line.startswith('#'):
                continue

            if line.startswith('export '):
                line = line[7:].strip()

            if '=' not in line:
                continue

            key, value = line.split('=', 1)
            key = key.strip()
            value = value.strip().strip('"').strip("'")

            if key:
                os.environ.setdefault(key, value)


# Suppress naive datetime warnings caused by Django admin internals querying
# DateTimeField (e.g. Pet.created_at) while USE_TZ=True is active.
warnings.filterwarnings(
    'ignore',
    message=r'.*received a naive datetime.*',
    category=RuntimeWarning,
    module=r'django\.db\.models\.fields',
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
env_path = BASE_DIR / '.env'
_load_environment_file(env_path)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

DEPLOYMENT_ENV = os.environ.get('DJANGO_ENV', 'development').strip().lower()
DEBUG = os.environ.get(
    'DEBUG', 'true' if DEPLOYMENT_ENV != 'production' else 'false'
).lower() in ('true', '1', 'yes')

SECRET_KEY = os.environ.get('SECRET_KEY', '')
if not SECRET_KEY:
    if not DEBUG:
        raise RuntimeError('SECRET_KEY must be set when DEBUG=False.')
    SECRET_KEY = 'django-insecure-development-only-change-me'

configured_hosts = os.environ.get('ALLOWED_HOSTS', '')
if not configured_hosts and not DEBUG:
    raise RuntimeError('ALLOWED_HOSTS must be set when DEBUG=False.')
ALLOWED_HOSTS = [h.strip() for h in configured_hosts.split(',') if h.strip()]
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]', 'testserver']

CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]
if not DEBUG and not CSRF_TRUSTED_ORIGINS:
    raise RuntimeError('CSRF_TRUSTED_ORIGINS must be set when DEBUG=False.')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Project apps
    'landing',
    'accounts',
    'branches',
    'patients',
    'appointments',
    'records',
    'inventory',
    'billing',
    'employees',
    'attendance',
    'notifications',
    'payroll',
    'pos.apps.PosConfig',
    'reports',
    'utils',
    'settings',
    'diagnostics',
    'disease_geo_mapping',
    'inquiries',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'settings.middleware.MaintenanceModeMiddleware',
    'settings.middleware.SessionTimeoutMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'FMHANIMALCLINIC.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notifications.context_processors.unread_notifications',
                'patients.context_processors.patient_stats.patient_stats',
                'settings.context_processors.clinic_settings',
                'settings.context_processors.landing_content',
                'inquiries.context_processors.new_inquiry_count',
                'settings.context_processors.legal_documents',
                'accounts.context_processors.navigation_modules',
            ],
        },
    },
]

WSGI_APPLICATION = 'FMHANIMALCLINIC.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_ENGINE = os.environ.get('DB_ENGINE', 'postgresql').strip().lower()

if DB_ENGINE != 'postgresql':
    raise ValueError('This project is configured for PostgreSQL only. Set DB_ENGINE=postgresql.')

if not DEBUG:
    required_database_values = ('DB_NAME', 'DB_USER', 'DB_PASSWORD', 'DB_HOST', 'DB_PORT')
    missing_database_values = [key for key in required_database_values if not os.environ.get(key)]
    if missing_database_values:
        raise RuntimeError(
            'Missing production database environment variables: '
            + ', '.join(missing_database_values)
        )

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'fmhclinic'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'postgres'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    },
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True
USE_L10N = True

USE_TZ = True

# Enable thousands grouping globally (for floatformat)
USE_THOUSAND_SEPARATOR = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', str(not DEBUG)).lower() in (
    'true', '1', 'yes'
)
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0' if DEBUG else '31536000'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/accounts/dashboard/'
AUTH_USER_MODEL = 'accounts.User'

# Session settings: expire after 24 hours of inactivity.
SESSION_COOKIE_AGE = 24 * 60 * 60
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True

# Email settings
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL', 'noreply@fmhanimalclinic.com')

# GROQ API settings for AI Diagnostics
GROQ_API_KEY = os.environ.get('GROQ_API_KEY', '')
if not DEBUG and not GROQ_API_KEY:
    raise RuntimeError('GROQ_API_KEY must be set when DEBUG=False.')

CLAMAV_ENABLED = os.environ.get('CLAMAV_ENABLED', 'false').lower() in ('true', '1', 'yes')
CLAMAV_REQUIRED = os.environ.get('CLAMAV_REQUIRED', str(not DEBUG)).lower() in ('true', '1', 'yes')

# Ensure logs directory exists
log_dir = BASE_DIR / 'logs'
log_dir.mkdir(exist_ok=True)

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'debug.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'fmh': {
            'handlers': ['console', 'file'] if not DEBUG else ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}


# =============================================================================
# Email Configuration (Gmail SMTP for OTP)
# =============================================================================

# Use console backend for development (prints emails to terminal)
# Switch to SMTP backend for production
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
if not DEBUG and (not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD):
    raise RuntimeError('EMAIL_HOST_USER and EMAIL_HOST_PASSWORD must be set when DEBUG=False.')
DEFAULT_FROM_EMAIL = os.environ.get(
    'EMAIL_HOST_USER', 'noreply@fmhanimalclinic.com')
