# Generated by Django 6.0.3 on 2026-08-18 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('employees', '0008_staffmember_default_custom_deductions'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailyattendance',
            name='unique_staff_date_attendance',
        ),
        migrations.RemoveConstraint(
            model_name='staffbiometricmapping',
            name='unique_device_user_id',
        ),
        migrations.RenameIndex(
            model_name='attendanceexception',
            new_name='attendance__staff_i_ab7a74_idx',
            old_name='attendance_a_staff_a_99a1b2_idx',
        ),
        migrations.RenameIndex(
            model_name='attendanceexception',
            new_name='attendance__excepti_53fb69_idx',
            old_name='attendance_a_exceptio_99a1b2_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancelog',
            new_name='attendance__externa_44d97c_idx',
            old_name='attendance_a_externa_99a1b2_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancelog',
            new_name='attendance__device__aa181d_idx',
            old_name='attendance_a_device__99a1b2_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancelog',
            new_name='attendance__sync_st_df4809_idx',
            old_name='attendance_a_sync_st_99a1b2_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyattendance',
            new_name='attendance__staff_i_ce26b7_idx',
            old_name='attendance_d_staff_a_99a1b2_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyattendance',
            new_name='attendance__attenda_1d90f9_idx',
            old_name='attendance_d_attenda_99a1b2_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyattendance',
            new_name='attendance__is_appr_f10c53_idx',
            old_name='attendance_d_is_appr_99a1b2_idx',
        ),
        migrations.RenameIndex(
            model_name='staffbiometricmapping',
            new_name='attendance__staff_i_99187d_idx',
            old_name='attendance_s_staff_i_99a1b2_idx',
        ),
        migrations.RenameIndex(
            model_name='staffbiometricmapping',
            new_name='attendance__device__b575fe_idx',
            old_name='attendance_s_device__99a1b2_idx',
        ),
        migrations.AlterUniqueTogether(
            name='dailyattendance',
            unique_together={('staff', 'attendance_date')},
        ),
        migrations.AlterUniqueTogether(
            name='staffbiometricmapping',
            unique_together={('device', 'external_user_id')},
        ),
    ]
