# Generated by Django 6.0.3 on 2026-08-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_dailyattendance_unique_staff_date_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricdevice',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Use this scanner as the default source for imported attendance files.'),
        ),
    ]
