# Generated by Django 6.0.3 on 2026-08-20 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_biometricdevice_is_primary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biometricdevice',
            name='is_primary',
        ),
    ]
