# Generated by Django 5.2 on 2026-08-27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_legacy_uploads(apps, schema_editor):
    MonthlyAttendanceSummary = apps.get_model('attendance', 'MonthlyAttendanceSummary')
    AttendanceUpload = apps.get_model('attendance', 'AttendanceUpload')
    periods = MonthlyAttendanceSummary.objects.values(
        'period_start', 'period_end', 'source_filename', 'uploaded_by_id'
    ).distinct()
    for period in periods:
        AttendanceUpload.objects.get_or_create(
            period_start=period['period_start'],
            period_end=period['period_end'],
            defaults={
                'source_filename': period['source_filename'] or 'Legacy import (original file unavailable)',
                'uploaded_by_id': period['uploaded_by_id'],
                'source_file': '',
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_restore_disease_geo_mapping_module'),
        ('attendance', '0009_monthlyattendance_review_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('source_file', models.FileField(upload_to='attendance/uploads/%Y/%m/')),
                ('source_filename', models.CharField(max_length=255)),
                ('unmatched_biometric_ids', models.JSONField(blank=True, default=list)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start', '-imported_at'],
                'constraints': [
                    models.UniqueConstraint(fields=('period_start', 'period_end'), name='unique_attendance_upload_month'),
                ],
            },
        ),
        migrations.RunPython(
            code=backfill_legacy_uploads,
            reverse_code=migrations.RunPython.noop,
        ),
    ]