# Generated by Django 6.0.3 on 2026-08-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_discard_imported_real_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='afternoon_in',
            field=models.TimeField(blank=True, help_text='Afternoon shift check-in time', null=True),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='afternoon_out',
            field=models.TimeField(blank=True, help_text='Afternoon shift check-out time', null=True),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='four_punch_complete',
            field=models.BooleanField(default=False, help_text='Are all 4 punches (morning in/out, afternoon in/out) present?'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='morning_in',
            field=models.TimeField(blank=True, help_text='Morning shift check-in time', null=True),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='morning_out',
            field=models.TimeField(blank=True, help_text='Morning shift check-out time', null=True),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='ot_hours_calculated',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Overtime hours calculated from OT_IN/OT_OUT timestamps', max_digits=5),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='ot_in',
            field=models.TimeField(blank=True, help_text='Overtime shift check-in time', null=True),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='ot_out',
            field=models.TimeField(blank=True, help_text='Overtime shift check-out time', null=True),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='punch_validation_error',
            field=models.TextField(blank=True, help_text='Error details if 4-punch validation failed'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='punch_validation_status',
            field=models.CharField(choices=[('PENDING', 'Pending Validation'), ('PASS', 'Passed 4-Punch Validation'), ('FAIL', 'Failed 4-Punch Validation'), ('FALLBACK', 'Using Fallback (No Granular Punches)')], default='PENDING', help_text='Result of 4-punch validation', max_length=50),
        ),
        migrations.AddField(
            model_name='monthlyattendancesummary',
            name='four_punch_validation_status',
            field=models.CharField(choices=[('PENDING', 'Validation Pending'), ('PASS', '100% Pass - All Records Valid'), ('PARTIAL', 'Partial Pass - Some Records Invalid'), ('FAIL', 'Failed - All Records Invalid'), ('NOT_APPLICABLE', 'Not Applicable - Using Fallback Data')], default='PENDING', help_text='Overall 4-punch validation status for this month', max_length=50),
        ),
        migrations.AddField(
            model_name='monthlyattendancesummary',
            name='four_punch_violations',
            field=models.JSONField(blank=True, default=list, help_text='List of dates/details with missing punches'),
        ),
        migrations.AddField(
            model_name='monthlyattendancesummary',
            name='four_punch_violations_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of days with incomplete punch records'),
        ),
        migrations.AddField(
            model_name='monthlyattendancesummary',
            name='required_working_days',
            field=models.PositiveIntegerField(default=0, help_text='Required working days for this period (cap for attendance)'),
        ),
        migrations.AddField(
            model_name='monthlyattendancesummary',
            name='required_working_days_first_half',
            field=models.PositiveIntegerField(default=0, help_text='Required working days for first half (1-15)'),
        ),
        migrations.AddField(
            model_name='monthlyattendancesummary',
            name='required_working_days_second_half',
            field=models.PositiveIntegerField(default=0, help_text='Required working days for second half (16-end)'),
        ),
    ]
