# Generated by Django 6.0.3 on 2026-09-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_dailyattendance_afternoon_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyattendancesummary',
            name='allowances',
        ),
    ]
