# Generated by Django 6.0.3 on 2026-09-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_remove_monthlyattendancesummary_allowances'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attendancelog',
            name='attendance__externa_44d97c_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancelog',
            name='attendance__device__aa181d_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancelog',
            name='attendance__sync_st_df4809_idx',
        ),
        migrations.RemoveField(
            model_name='biometricdevice',
            name='branch',
        ),
        migrations.DeleteModel(
            name='AttendanceLog',
        ),
        migrations.DeleteModel(
            name='BiometricDevice',
        ),
    ]
