# Generated by Django 6.0.3 on 2026-09-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_scheduledreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledreport',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='scheduledreport',
            name='created_by',
        ),
        migrations.RemoveConstraint(
            model_name='scheduledreportdelivery',
            name='unique_report_period_delivery',
        ),
        migrations.RemoveField(
            model_name='scheduledreportdelivery',
            name='report',
        ),
        migrations.DeleteModel(
            name='ScheduledReport',
        ),
        migrations.DeleteModel(
            name='ScheduledReportDelivery',
        ),
    ]
