# Generated by Django 5.2.7 on 2026-02-27 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_rename_address_line_1_branch_address_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('Purchase', 'Purchase'), ('Return', 'Return'), ('Damage', 'Damaged Stock'), ('Expiration', 'Expired'), ('Correction', 'Inventory Correction')], default='Purchase', max_length=20)),
                ('reference', models.CharField(help_text='e.g., PO123', max_length=50)),
                ('date', models.DateField()),
                ('quantity', models.IntegerField(help_text='Positive for additions, negative for subtractions')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reason', models.CharField(blank=True, help_text='e.g., Damaged stock', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='branches.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='inventory.product')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
