# Generated by Django 5.2.7 on 2026-03-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockadjustment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='item_type',
            field=models.CharField(choices=[('PRODUCT', 'Product'), ('MEDICATION', 'Medication')], default='PRODUCT', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock_level',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Return', 'Return'), ('Damage', 'Damaged Stock'), ('Expiration', 'Expired'), ('Correction', 'Inventory Correction'), ('Sale', 'Sale')], default='Purchase', max_length=20),
        ),
    ]
