# Generated by Django 6.0 on 2026-03-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_stockadjustment_adjustment_type_stocktransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('Purchase', 'Add Stock (New Purchase / Delivery)'), ('Return', 'Add Stock (Customer Return)'), ('Transfer In', 'Add Stock (Received from another branch)'), ('Damage', 'Remove Stock (Damaged / Broken)'), ('Expiration', 'Remove Stock (Expired)'), ('Sale', 'Remove Stock (Sold offline / manual)'), ('Reservation', 'Remove Stock (Reserved)'), ('Transfer Out', 'Remove Stock (Sent to another branch)'), ('Correction', 'Inventory Update (Manual Count Correction)')], default='Purchase', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='quantity',
            field=models.IntegerField(help_text='Enter the number of items. Removals are calculated automatically.'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason',
            field=models.CharField(blank=True, help_text='e.g., Damaged, Expired, Returned', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='reference',
            field=models.CharField(help_text='e.g., Receipt #, Invoice ID, or N/A', max_length=50),
        ),
    ]
