# Generated by Django 6.0 on 2026-03-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_product_deleted_at_product_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Released', 'Released'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
