# Generated by Django 6.0 on 2026-03-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
