# Generated by Django 6.0 on 2026-03-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_reservation_pickup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_consumable',
            field=models.BooleanField(default=False, help_text='True for single-use / consumable items (medicines, medical supplies)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_type',
            field=models.CharField(choices=[('Product', 'Product'), ('Medication', 'Medication'), ('Accessories', 'Accessories'), ('Medical Supplies', 'Medical Supplies')], default='Product', max_length=20),
        ),
    ]
