# Generated by Django 6.0.3 on 2026-03-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_branch_badge_label_branch_display_order_and_more'),
        ('inventory', '0013_product_is_consumable_alter_product_item_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['branch', 'item_type'], name='inventory_p_branch__d8816f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock_quantity'], name='inventory_p_stock_q_e1fd3c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_available'], name='inventory_p_is_avai_21f017_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['branch', 'created_at'], name='inventory_p_branch__4c339b_idx'),
        ),
    ]
