# Generated by Django 6.0.3 on 2026-04-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_update_stockadjustment_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('ADD', 'Add Stock (Restock / Manual Addition)'), ('REMOVE', 'Remove Stock (Adjustment / Manual Deduction)'), ('SALE', 'Remove Stock (Sale)'), ('TRANSFER_IN', 'Add Stock (Transfer Received)'), ('TRANSFER_OUT', 'Remove Stock (Transfer Sent)')], default='ADD', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='cost_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Optional: Cost per unit for restocks', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='quantity',
            field=models.IntegerField(help_text='Number of items to add or remove.'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='reference',
            field=models.CharField(blank=True, default='', help_text='Optional: Receipt #, Invoice ID, or leave blank', max_length=50),
        ),
    ]
