# Generated by Django 6.0.3 on 2026-05-03

from django.db import migrations


def forwards(apps, schema_editor):
    StockTransfer = apps.get_model('inventory', 'StockTransfer')
    Product = apps.get_model('inventory', 'Product')
    main_products = Product.objects.filter(branch__is_main_source=True)

    for transfer in StockTransfer.objects.select_related('source_product__branch').all():
        if transfer.source_product.branch.is_main_source:
            continue

        main_product = main_products.filter(sku=transfer.source_product.sku).first()
        if main_product and main_product.pk != transfer.source_product_id:
            transfer.source_product_id = main_product.pk
            transfer.save(update_fields=['source_product'])


def backwards(apps, schema_editor):
    # Intentionally left as a no-op. The historical source branch is not reliably reconstructible
    # once transfers are corrected to the main stock source.
    return


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_clone_inventory_with_flexible_branch_matching'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]