# Generated by Django 6.0.3 on 2026-07-10 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_reassign_transfer_sources_to_main_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
    ]
