# Generated by Django 6.0.3 on 2026-07-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_remove_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_type',
            field=models.CharField(choices=[('piece', 'Per Piece'), ('batch', 'Per Batch/Pack')], default='piece', help_text='How this item is sold or reserved', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measurement',
            field=models.CharField(choices=[('piece', 'Piece'), ('tablet', 'Tablet'), ('capsule', 'Capsule'), ('vial', 'Vial'), ('bottle', 'Bottle'), ('box', 'Box'), ('pack', 'Pack'), ('strip', 'Strip'), ('sachet', 'Sachet'), ('tube', 'Tube'), ('ml', 'Milliliter (ml)'), ('l', 'Liter (L)'), ('g', 'Gram (g)'), ('kg', 'Kilogram (kg)'), ('set', 'Set')], default='piece', help_text='Primary unit used for inventory display and reservations', max_length=20),
        ),
    ]
