# Generated by Django 6.0.3 on 2026-07-11 08:02

import settings.utils
from django.db import migrations, models


def populate_inventory_units(apps, schema_editor):
    """Backfill inventory products with name-based units and sale types."""
    Product = apps.get_model('inventory', 'Product')

    unit_map = {
        'colimoxyn': 'box',
        'lc dox': 'box',
        'beloxicam': 'box',
        'supreme pro plus': 'box',
        'renal vet': 'box',
        'nefrotec ds': 'box',
        'veto skin': 'bottle',
        'otiderm': 'bottle',
        'papi ob': 'box',
        'scavon': 'bottle',
        'collar': 'piece',
        'leash with harness': 'set',
        'dental care kit': 'set',
        'single frame door/cage': 'piece',
        'food bowl': 'piece',
        'pet slicker brush': 'piece',
        'ketazole shampoo': 'bottle',
        'anti tick and flea': 'bottle',
        'scrubs': 'set',
        'premium goats milk': 'can',
        'paleo pet': 'pack',
    }

    sale_type_by_unit = {
        'piece': 'piece',
    }

    for name, unit in unit_map.items():
        sale_type = sale_type_by_unit.get(unit, 'batch')
        Product.objects.filter(name__iexact=name).update(
            unit_of_measurement=unit,
            sale_type=sale_type,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_product_sale_type_product_unit_of_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_of_measurement',
            field=models.CharField(choices=settings.utils.get_inventory_unit_choices, default='piece', help_text='Primary unit used for inventory display and reservations', max_length=50),
        ),
        migrations.RunPython(populate_inventory_units, migrations.RunPython.noop),
    ]
