# Generated by Django 6.0.3 on 2026-07-11 08:13

import settings.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_product_unit_of_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_type',
            field=models.CharField(choices=settings.utils.get_inventory_sale_type_choices, default='piece', help_text='How this item is sold or reserved', max_length=20),
        ),
    ]
