# Generated by assistant

import settings.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_convert_sale_type_to_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_type',
            field=models.CharField(choices=settings.utils.get_inventory_item_type_choices, default='Product', max_length=50),
        ),
    ]
