# Generated by Django 5.2.7 on 2026-02-27 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_alter_vetschedule_unique_together_and_more'),
        ('patients', '0002_alter_pet_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Temperature in °C', max_digits=4, null=True)),
                ('diagnosis', models.TextField()),
                ('treatment', models.TextField()),
                ('date_recorded', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.pet')),
                ('vet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='employees.staffmember')),
            ],
            options={
                'ordering': ['-date_recorded', '-created_at'],
            },
        ),
    ]
