# Generated by Django 5.2.7 on 2026-03-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='record_type',
            field=models.CharField(choices=[('Vaccination Record', 'Vaccination Record'), ('Surgery', 'Surgery'), ('Checkup', 'Checkup'), ('General', 'General')], default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
