# Generated by Django 5.2.7 on 2026-03-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_medicalrecord_description_medicalrecord_record_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='description',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='record_type',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='ff_up',
            field=models.DateField(blank=True, null=True, verbose_name='FF-UP (Follow-Up)'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='history_clinical_signs',
            field=models.TextField(blank=True, null=True, verbose_name='History / Clinical Signs'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='rx',
            field=models.TextField(blank=True, null=True, verbose_name='Rx (Prescription)'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='treatment',
            field=models.TextField(verbose_name='Tx (Treatment)'),
        ),
    ]
