# Generated by Django 5.2.7 on 2026-03-03 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_rename_address_line_1_branch_address_and_more'),
        ('records', '0003_remove_medicalrecord_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='branches.branch'),
        ),
    ]
