# Generated by Django 6.0 on 2026-03-05 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_vetschedule_unique_together_and_more'),
        ('records', '0004_medicalrecord_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Temperature in °C', max_digits=4, null=True)),
                ('history_clinical_signs', models.TextField(blank=True, null=True, verbose_name='History / Clinical Signs')),
                ('treatment', models.TextField(blank=True, null=True, verbose_name='Tx (Treatment)')),
                ('rx', models.TextField(blank=True, null=True, verbose_name='Rx (Prescription)')),
                ('ff_up', models.DateField(blank=True, null=True, verbose_name='FF-UP (Follow-Up)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='records.medicalrecord')),
                ('vet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_entries', to='employees.staffmember')),
            ],
            options={
                'ordering': ['-date_recorded', '-created_at'],
            },
        ),
    ]
