# Generated by Django 6.0 on 2026-03-07 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_staffmember_deleted_at_staffmember_is_deleted'),
        ('records', '0006_populate_recordentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='treatment',
            field=models.TextField(blank=True, verbose_name='Tx (Treatment)'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='vet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='employees.staffmember'),
        ),
    ]
