# Generated by Django 6.0 on 2026-03-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_alter_medicalrecord_treatment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordentry',
            name='action_required',
            field=models.CharField(choices=[('DISCHARGED', 'Discharged (No Further Action)'), ('MONITOR', 'Admit for Monitoring'), ('SURGERY', 'Admit for Surgery'), ('DIAGNOSTICS', 'Pending Diagnostics/Lab')], default='DISCHARGED', help_text='The next step required after this consultation.', max_length=20, verbose_name='Required Action'),
        ),
    ]
