# Generated by Django 6.0 on 2026-03-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_recordentry_action_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordentry',
            name='action_required',
            field=models.CharField(choices=[('HEALTHY', 'Healthy (No Further Action)'), ('MONITOR', 'Under Monitoring'), ('TREATMENT', 'In Treatment'), ('SURGERY', 'In Surgery'), ('DIAGNOSTICS', 'Pending Diagnostics'), ('CRITICAL', 'Critical')], default='HEALTHY', help_text='The next step required after this consultation.', max_length=20, verbose_name='Required Action'),
        ),
    ]
