# Generated by Django 6.0 on 2026-03-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_alter_recordentry_action_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='source',
            field=models.CharField(choices=[('PORTAL', 'Portal (Registered User)'), ('WALKIN', 'Walk-in (Guest)')], default='PORTAL', help_text='Whether this record is for a portal registered user or walk-in guest.', max_length=10, verbose_name='Client Source'),
        ),
        migrations.AddField(
            model_name='recordentry',
            name='source',
            field=models.CharField(choices=[('PORTAL', 'Portal (Registered User)'), ('WALKIN', 'Walk-in (Guest)')], default='PORTAL', help_text='Whether this entry is for a portal registered user or walk-in guest.', max_length=10, verbose_name='Client Source'),
        ),
    ]
