# Generated by Django 6.0 on 2026-03-16 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_medicalrecord_source_recordentry_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='source',
        ),
        migrations.RemoveField(
            model_name='recordentry',
            name='source',
        ),
    ]
