# Generated by Django 6.0.3 on 2026-03-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_branch_badge_label_branch_display_order_and_more'),
        ('employees', '0005_vetschedule_employees_v_branch__375b92_idx_and_more'),
        ('patients', '0013_pet_clinical_status_alter_pet_status'),
        ('records', '0011_remove_medicalrecord_source_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['pet', 'created_at'], name='records_med_pet_id_35ac3e_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['date_recorded'], name='records_med_date_re_3e382e_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['branch', 'date_recorded'], name='records_med_branch__0ca8a5_idx'),
        ),
        migrations.AddIndex(
            model_name='recordentry',
            index=models.Index(fields=['record', 'date_recorded'], name='records_rec_record__104056_idx'),
        ),
        migrations.AddIndex(
            model_name='recordentry',
            index=models.Index(fields=['date_recorded'], name='records_rec_date_re_c5ba3b_idx'),
        ),
    ]
