# Generated by Django 6.0.3 on 2026-04-25 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_medicalrecord_lab_results_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordentry',
            name='diagnostic_tests',
        ),
    ]
