# Generated by Django 6.0.3 on 2026-09-02 14:43

import records.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_medicalfile_medicalfileaccesslog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='medicalfileaccesslog',
            new_name='records_med_medical_18ee7c_idx',
            old_name='records_med_medical_7b8ea0_idx',
        ),
        migrations.AlterField(
            model_name='medicalfile',
            name='file',
            field=models.FileField(upload_to=records.models.medical_file_upload_path, validators=[records.models.validate_medical_file]),
        ),
    ]
