# Generated by Django 5.2.7 on 2026-02-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='follow_up_end_date',
            field=models.DateField(blank=True, help_text='Optional end date for a follow-up range', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='follow_up_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
