# Generated by Django 5.2.7 on 2026-03-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_followup_follow_up_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the related object (e.g., Appointment ID or Product ID)', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('FOLLOW_UP', 'Follow-up'), ('APPOINTMENT', 'Appointment'), ('INVENTORY_RESTOCK', 'Inventory Restock'), ('LOW_INVENTORY', 'Low Inventory'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
    ]
