# Generated by Django 5.2.7 on 2026-03-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_related_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('FOLLOW_UP', 'Follow-up'), ('APPOINTMENT', 'Appointment'), ('INVENTORY_RESTOCK', 'Inventory Restock'), ('LOW_INVENTORY', 'Low Inventory'), ('PRODUCT_RESERVATION', 'Product Reservation'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
    ]
