# Generated by Django 6.0.3 on 2026-03-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_notificatio_user_id_427e4b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('FOLLOW_UP', 'Follow-up'), ('APPOINTMENT', 'Appointment'), ('APPOINTMENT_CONFIRMED', 'Appointment Confirmed'), ('APPOINTMENT_CANCELLED', 'Appointment Cancelled'), ('APPOINTMENT_RESCHEDULED', 'Appointment Rescheduled'), ('RESERVATION_APPROVED', 'Reservation Approved'), ('RESERVATION_REJECTED', 'Reservation Rejected'), ('RESERVATION_READY', 'Reservation Ready'), ('FOLLOW_UP_OVERDUE', 'Follow-up Overdue'), ('INVENTORY_RESTOCK', 'Inventory Restock'), ('LOW_INVENTORY', 'Low Inventory'), ('LOW_STOCK_ALERT', 'Low Stock Alert'), ('PRODUCT_RESERVATION', 'Product Reservation'), ('STATEMENT_RELEASED', 'Statement Released'), ('MEDICAL_RECORD_UPDATE', 'Medical Record Update'), ('GENERAL', 'General')], default='GENERAL', max_length=30),
        ),
    ]
