# Generated by Django 6.0.3 on 2026-04-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_notification_module_context_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('FOLLOW_UP', 'Follow-up'), ('APPOINTMENT', 'Appointment'), ('APPOINTMENT_CONFIRMED', 'Appointment Confirmed'), ('APPOINTMENT_CANCELLED', 'Appointment Cancelled'), ('APPOINTMENT_RESCHEDULED', 'Appointment Rescheduled'), ('APPOINTMENT_REMINDER_1', 'Appointment Reminder (1 Day)'), ('APPOINTMENT_REMINDER_2', 'Appointment Reminder (3 Hours)'), ('RESERVATION_APPROVED', 'Reservation Approved'), ('RESERVATION_REJECTED', 'Reservation Rejected'), ('RESERVATION_READY', 'Reservation Ready'), ('FOLLOW_UP_OVERDUE', 'Follow-up Overdue'), ('INVENTORY_RESTOCK', 'Inventory Restock'), ('LOW_INVENTORY', 'Low Inventory'), ('LOW_STOCK_ALERT', 'Low Stock Alert'), ('PRODUCT_RESERVATION', 'Product Reservation'), ('STATEMENT_RELEASED', 'Statement Released'), ('MEDICAL_RECORD_UPDATE', 'Medical Record Update'), ('INQUIRY_NEW', 'New Inquiry'), ('INQUIRY_RESPONDED', 'Inquiry Responded'), ('INQUIRY_ARCHIVED', 'Inquiry Archived'), ('STOCK_TRANSFER_REQUESTED', 'Stock Transfer Requested'), ('STOCK_TRANSFER_APPROVED', 'Stock Transfer Approved'), ('STOCK_TRANSFER_REJECTED', 'Stock Transfer Rejected'), ('STOCK_TRANSFER_COMPLETED', 'Stock Transfer Completed'), ('PAYROLL_GENERATED', 'Payroll Generated'), ('PAYROLL_RELEASED', 'Payroll Released'), ('GENERAL', 'General')], default='GENERAL', max_length=30),
        ),
    ]
