# Generated by Django 6.0.3 on 2026-07-20 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0006_branch_is_main_source'),
        ('patients', '0018_pet_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseGeoMappingInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('case_count', models.PositiveIntegerField(default=1)),
                ('trend_score', models.FloatField(default=0.0)),
                ('seasonality', models.CharField(blank=True, max_length=80)),
                ('summary', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_geo_insights', to='branches.branch')),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease_geo_insights', to='patients.pet')),
            ],
            options={
                'verbose_name': 'Disease Geo Mapping Insight',
                'verbose_name_plural': 'Disease Geo Mapping Insights',
                'ordering': ['-created_at'],
            },
        ),
    ]
