# Generated by Django 6.0.3 on 2026-08-17 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_branch_is_main_source'),
        ('disease_geo_mapping', '0002_seed_module_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseDetailedPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=150)),
                ('confidence', models.FloatField(default=0.0)),
                ('case_count', models.PositiveIntegerField(default=1)),
                ('disease_breakdown', models.TextField(blank=True, help_text='Main disease description for animals')),
                ('specific_examples', models.TextField(blank=True, help_text='JSON list of 5 specific disease examples')),
                ('prevention_guidance', models.TextField(blank=True, help_text='Animal-specific prevention and care guidance')),
                ('recommended_actions', models.TextField(blank=True, help_text='Clinical and operational actions for clinic staff')),
                ('clinical_summary', models.TextField(blank=True, help_text='Specific clinical presentation in animals')),
                ('suggested_investigations', models.TextField(blank=True, help_text='Diagnostic tests and investigations')),
                ('location_branch', models.CharField(blank=True, max_length=120)),
                ('time_period_start', models.DateField(blank=True, null=True)),
                ('time_period_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_predictions', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Disease Detailed Prediction',
                'verbose_name_plural': 'Disease Detailed Predictions',
                'ordering': ['-created_at'],
            },
        ),
    ]
