# Generated by Django 6.0.3 on 2026-09-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease_geo_mapping', '0003_diseasedetailedprediction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseasegeomappinginsight',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='diseasegeomappinginsight',
            name='pet',
        ),
        migrations.DeleteModel(
            name='DiseaseDetailedPrediction',
        ),
        migrations.DeleteModel(
            name='DiseaseGeoMappingInsight',
        ),
    ]
