# Generated by Django 6.0 on 2026-03-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='FMH Animal Clinic', help_text='Clinic display name', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Clinic logo image', null=True, upload_to='clinic/')),
                ('email', models.EmailField(blank=True, help_text='Primary contact email', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Primary phone number', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Main clinic address')),
                ('tagline', models.CharField(blank=True, help_text='Clinic slogan or tagline', max_length=255)),
                ('license_number', models.CharField(blank=True, help_text='Business or veterinary license number', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clinic Profile',
                'verbose_name_plural': 'Clinic Profile',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('decimal', 'Decimal'), ('json', 'JSON')], default='string', max_length=20)),
                ('category', models.CharField(choices=[('CLINIC', 'Clinic Information'), ('APPOINTMENT', 'Appointment Settings'), ('INVENTORY', 'Inventory Settings'), ('NOTIFICATION', 'Notification Settings'), ('PAYROLL', 'Payroll Settings'), ('SYSTEM', 'System Settings'), ('MEDICAL', 'Medical Records Settings')], default='SYSTEM', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_sensitive', models.BooleanField(default=False, help_text='Mark as sensitive for API keys, passwords, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'ordering': ['category', 'key'],
            },
        ),
    ]
