# Generated by Django 6.0 on 2026-03-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_seed_default_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(default='bx-star', help_text="Boxicons class name (e.g., 'bx-heart', 'bx-anchor')", max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional description for the value')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Core Value',
                'verbose_name_plural': 'Core Values',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text="The main stat value (e.g., '3', 'AI', '24/7')", max_length=50)),
                ('label', models.CharField(help_text="Description label (e.g., 'Clinic Branches')", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Statistic',
                'verbose_name_plural': 'Hero Statistics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SectionContent',
            fields=[
                ('section_type', models.CharField(choices=[('HERO', 'Hero Section'), ('MISSION', 'Mission Section'), ('VISION', 'Vision Section'), ('SERVICES_INTRO', 'Services Introduction'), ('VETS_INTRO', 'Veterinarians Introduction'), ('CORE_VALUES_INTRO', 'Core Values Introduction')], max_length=20, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Section background or feature image', null=True, upload_to='content/sections/')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section Content',
                'verbose_name_plural': 'Section Contents',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='bx-plus-medical', help_text="Boxicons class name (e.g., 'bx-injection', 'bx-bath')", max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Service card background image', null=True, upload_to='content/services/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(help_text="Professional title (e.g., 'Senior Veterinarian')", max_length=100)),
                ('bio', models.TextField(help_text='Short biography')),
                ('photo', models.ImageField(blank=True, help_text='Profile photo', null=True, upload_to='content/veterinarians/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veterinarian',
                'verbose_name_plural': 'Veterinarians',
                'ordering': ['order'],
            },
        ),
    ]
