# Generated by Django 6.0 on 2026-03-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_seed_landing_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicprofile',
            name='logo',
            field=models.ImageField(blank=True, help_text='Clinic logo image', null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='sectioncontent',
            name='image',
            field=models.ImageField(blank=True, help_text='Section background or feature image', null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Service card background image', null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='veterinarian',
            name='photo',
            field=models.ImageField(blank=True, help_text='Profile photo', null=True, upload_to='image/'),
        ),
    ]
