# Generated by Django 6.0 on 2026-03-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_update_image_upload_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectioncontent',
            name='section_type',
            field=models.CharField(choices=[('HERO', 'Hero Section'), ('MISSION', 'Mission Section'), ('VISION', 'Vision Section'), ('SERVICES_INTRO', 'Services Introduction'), ('VETS_INTRO', 'Veterinarians Introduction'), ('CORE_VALUES_INTRO', 'Core Values Introduction'), ('APPOINTMENT', 'Appointment Section')], max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
