# Generated by Django 6.0.3 on 2026-03-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_update_image_upload_paths'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for this status (e.g., "Healthy")', max_length=100)),
                ('code', models.CharField(help_text='Unique code for internal use (e.g., "HEALTHY")', max_length=30, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description for staff reference')),
                ('color', models.CharField(default='#4caf50', help_text='Color code for visual indication (e.g., "#4caf50" for green)', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive statuses will not appear in patient forms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clinical Status',
                'verbose_name_plural': 'Clinical Statuses',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReasonForVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for this reason (e.g., "General Consultation")', max_length=100)),
                ('code', models.CharField(help_text='Unique code for internal use (e.g., "GENERAL")', max_length=30, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description for staff reference')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive reasons will not appear in booking forms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reason for Visit',
                'verbose_name_plural': 'Reasons for Visit',
                'ordering': ['order', 'name'],
            },
        ),
    ]
