# Generated by Django 6.0.3 on 2026-03-28 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_sectioncontent_section_type'),
        ('settings', '0008_seed_default_reasons_for_visit'),
    ]

    operations = [
    ]
