# Generated by Django 6.0.3 on 2026-03-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_merge_20260328_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectioncontent',
            name='section_type',
            field=models.CharField(choices=[('HERO', 'Hero Section'), ('MISSION', 'Mission Section'), ('VISION', 'Vision Section'), ('SERVICES_INTRO', 'Services Introduction'), ('VETS_INTRO', 'Veterinarians Introduction'), ('CORE_VALUES_INTRO', 'Core Values Introduction')], max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
