# Generated by Django 6.0.3 on 2026-04-04 12:19

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_alter_sectioncontent_section_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicprofile',
            name='logo',
            field=models.ImageField(blank=True, help_text='Supported formats: .png, .jpeg (Max 10MB)', null=True, upload_to='image/', validators=[utils.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='sectioncontent',
            name='image',
            field=models.ImageField(blank=True, help_text='Supported formats: .png, .jpeg (Max 10MB)', null=True, upload_to='image/', validators=[utils.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Supported formats: .png, .jpeg (Max 10MB)', null=True, upload_to='image/', validators=[utils.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='veterinarian',
            name='photo',
            field=models.ImageField(blank=True, help_text='Supported formats: .png, .jpeg (Max 10MB)', null=True, upload_to='image/', validators=[utils.validators.validate_image_file]),
        ),
    ]
