# Generated by Django 6.0.3 on 2026-04-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_alter_clinicprofile_logo_alter_sectioncontent_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('TOS', 'Terms of Service'), ('PRIVACY', 'Privacy Policy')], help_text='Type of legal document', max_length=10, unique=True)),
                ('title', models.CharField(help_text='Display title (e.g., "Terms of Service")', max_length=255)),
                ('content', models.TextField(help_text='Full document content (supports HTML formatting)')),
                ('version', models.CharField(default='1.0', help_text='Document version number', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Only active documents are shown to users')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Legal Document',
                'verbose_name_plural': 'Legal Documents',
                'ordering': ['document_type'],
            },
        ),
    ]
