# Generated by GitHub Copilot

from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_module_code'),
        ('settings', '0012_legaldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicprofile',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook profile/page URL'),
        ),
        migrations.AddField(
            model_name='clinicprofile',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Optional square favicon. Recommended 64x64 or 128x128.', null=True, upload_to='image/', validators=[utils.validators.validate_image_file]),
        ),
        migrations.AddField(
            model_name='clinicprofile',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL'),
        ),
        migrations.AddField(
            model_name='clinicprofile',
            name='logo_dark',
            field=models.ImageField(blank=True, help_text='Optional dark logo variant for light backgrounds.', null=True, upload_to='image/', validators=[utils.validators.validate_image_file]),
        ),
        migrations.AddField(
            model_name='clinicprofile',
            name='logo_light',
            field=models.ImageField(blank=True, help_text='Optional light logo variant for dark backgrounds.', null=True, upload_to='image/', validators=[utils.validators.validate_image_file]),
        ),
        migrations.AddField(
            model_name='clinicprofile',
            name='messenger_url',
            field=models.URLField(blank=True, help_text='Messenger link URL'),
        ),
        migrations.AddField(
            model_name='clinicprofile',
            name='tiktok_url',
            field=models.URLField(blank=True, help_text='TikTok profile URL'),
        ),
        migrations.AddField(
            model_name='clinicprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who updated this clinic profile.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_clinic_profiles', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='clinicprofile',
            name='website_url',
            field=models.URLField(blank=True, help_text='Official clinic website URL'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='publish_at',
            field=models.DateTimeField(blank=True, help_text='Optional publish date/time. If set, document appears only when date is reached.', null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='require_reconsent',
            field=models.BooleanField(default=False, help_text='When enabled, users should be prompted to re-accept this updated document.'),
        ),
    ]
