# Generated by Django 6.0.3 on 2026-04-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_clinicprofile_branding_legal_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicprofile',
            name='favicon',
        ),
        migrations.RemoveField(
            model_name='clinicprofile',
            name='logo_dark',
        ),
        migrations.RemoveField(
            model_name='clinicprofile',
            name='logo_light',
        ),
        migrations.RemoveField(
            model_name='clinicprofile',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='clinicprofile',
            name='website_url',
        ),
        migrations.RemoveField(
            model_name='legaldocument',
            name='publish_at',
        ),
        migrations.RemoveField(
            model_name='legaldocument',
            name='require_reconsent',
        ),
    ]
