# Generated by Django 6.0.3 on 2026-04-24 07:37

from django.db import migrations, models


def copy_tagline_to_slogan(apps, schema_editor):
    ClinicProfile = apps.get_model('settings', 'ClinicProfile')
    for profile in ClinicProfile.objects.all():
        if not profile.clinic_slogan and getattr(profile, 'tagline', ''):
            profile.clinic_slogan = profile.tagline
            profile.save(update_fields=['clinic_slogan'])


def copy_slogan_to_tagline(apps, schema_editor):
    ClinicProfile = apps.get_model('settings', 'ClinicProfile')
    for profile in ClinicProfile.objects.all():
        if getattr(profile, 'clinic_slogan', ''):
            profile.tagline = profile.clinic_slogan
            profile.save(update_fields=['tagline'])


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_remove_clinicprofile_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicprofile',
            name='clinic_slogan',
            field=models.CharField(blank=True, help_text='Short landing-page slogan displayed under the title', max_length=255),
        ),
        migrations.AddField(
            model_name='clinicprofile',
            name='clinic_title',
            field=models.CharField(blank=True, help_text='Main landing-page title displayed beside the logo', max_length=255),
        ),
        migrations.AddField(
            model_name='clinicprofile',
            name='hero_description',
            field=models.TextField(blank=True, help_text='Landing-page hero description text'),
        ),
        migrations.RunPython(copy_tagline_to_slogan, copy_slogan_to_tagline),
        migrations.RemoveField(
            model_name='clinicprofile',
            name='tagline',
        ),
    ]
