# Generated by Django 6.0.3 on 2026-04-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_remove_clinicprofile_tagline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('normal_range', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Diagnostic Test',
                'verbose_name_plural': 'Diagnostic Tests',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecordTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('section', models.CharField(choices=[('HISTORY', 'History / Clinical Signs'), ('TREATMENT', 'Treatment (Tx)'), ('PRESCRIPTION', 'Prescription (Rx)'), ('LAB_RESULTS', 'Lab Results')], max_length=20)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medical Record Template',
                'verbose_name_plural': 'Medical Record Templates',
                'ordering': ['section', 'order', 'name'],
            },
        ),
    ]
