# Generated by Django 6.0.3 on 2026-04-25 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_remove_recordentry_diagnostic_tests'),
        ('settings', '0016_diagnostictest_medicalrecordtemplate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiagnosticTest',
        ),
        migrations.DeleteModel(
            name='MedicalRecordTemplate',
        ),
    ]
