# Generated by Django 6.0.3 on 2026-04-26 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_branch_badge_label_branch_display_order_and_more'),
        ('settings', '0017_delete_diagnostictest_delete_medicalrecordtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarian',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Primary branch assignment for this veterinarian', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veterinarians', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='credentials',
            field=models.CharField(blank=True, help_text='Professional credentials or certification string', max_length=255),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='email',
            field=models.EmailField(blank=True, help_text='Direct contact email', max_length=254),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook profile/page URL'),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL'),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='messenger_url',
            field=models.URLField(blank=True, help_text='Messenger link URL'),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='phone',
            field=models.CharField(blank=True, help_text='Direct contact number', max_length=20),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='specialization',
            field=models.CharField(blank=True, help_text='Area of specialization (e.g., surgery, internal medicine)', max_length=255),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='tiktok_url',
            field=models.URLField(blank=True, help_text='TikTok profile URL'),
        ),
    ]
