# Generated by Django 6.0.3 on 2026-04-26 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0018_veterinarian_branch_veterinarian_credentials_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veterinarian',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='veterinarian',
            name='credentials',
        ),
        migrations.RemoveField(
            model_name='veterinarian',
            name='email',
        ),
        migrations.RemoveField(
            model_name='veterinarian',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='veterinarian',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='veterinarian',
            name='messenger_url',
        ),
        migrations.RemoveField(
            model_name='veterinarian',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='veterinarian',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='veterinarian',
            name='tiktok_url',
        ),
    ]
