# Generated by Django 6.0.3 on 2026-04-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0020_sectioncontent_hero_subtitle_split'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoreValue',
        ),
        migrations.AlterField(
            model_name='sectioncontent',
            name='section_type',
            field=models.CharField(choices=[('HERO', 'Hero Section'), ('MISSION', 'Mission Section'), ('VISION', 'Vision Section'), ('SERVICES_INTRO', 'Services Introduction'), ('VETS_INTRO', 'Veterinarians Introduction')], max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
