# Generated by Django 6.0.3 on 2026-05-02 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_shift_type_option'),
        ('settings', '0022_alter_sectioncontent_section_type'),
    ]

    operations = [
    ]
