# Generated by Django 6.0.2 on 2026-03-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_pet_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Age in years (if DOB unknown)', null=True),
        ),
    ]
