# Generated by Django 6.0.2 on 2026-03-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_pet_date_of_birth_alter_pet_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='age',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='pet',
            name='dob_or_age',
            field=models.CharField(blank=True, help_text='Date of birth or age (e.g., "2020-01-15" or "3 years")', max_length=50, verbose_name='D.O.B / Age'),
        ),
    ]
