# Generated by Django 6.0 on 2026-03-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_pet_age_remove_pet_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='dob_or_age',
        ),
        migrations.AddField(
            model_name='pet',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth', null=True, verbose_name='Date of Birth'),
        ),
    ]
