# Generated by Django 6.0 on 2026-03-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_dob_to_date_field_and_clinic_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture for the pet', null=True, upload_to='pets/'),
        ),
    ]
