# Generated by Django 6.0 on 2026-03-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_add_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload a photo of your pet', null=True, upload_to='pet_photos/'),
        ),
    ]
