# Generated by Django 6.0 on 2026-03-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_remove_pet_profile_picture_pet_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('HEALTHY', 'Healthy'), ('MONITOR', 'Monitor'), ('TREATMENT', 'In Treatment'), ('CRITICAL', 'Critical')], default='HEALTHY', max_length=20),
        ),
    ]
