# Generated by Django 6.0 on 2026-03-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_pet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('HEALTHY', 'Healthy'), ('MONITOR', 'Under Monitoring'), ('TREATMENT', 'In Treatment'), ('SURGERY', 'In Surgery'), ('DIAGNOSTICS', 'Pending Diagnostics'), ('CRITICAL', 'Critical')], default='HEALTHY', max_length=20),
        ),
    ]
