# Generated by Django 6.0 on 2026-03-08 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_alter_pet_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='guest_owner_address',
            field=models.TextField(blank=True, help_text='Full address of the owner', verbose_name='Owner Address'),
        ),
        migrations.AddField(
            model_name='pet',
            name='guest_owner_email',
            field=models.EmailField(blank=True, help_text='Email address for the owner', max_length=254, verbose_name='Owner Email'),
        ),
        migrations.AddField(
            model_name='pet',
            name='guest_owner_name',
            field=models.CharField(blank=True, help_text='Full name of the owner (for walk-in patients without an account)', max_length=200, verbose_name='Owner Name'),
        ),
        migrations.AddField(
            model_name='pet',
            name='guest_owner_phone',
            field=models.CharField(blank=True, help_text='Contact number for the owner', max_length=20, verbose_name='Owner Phone'),
        ),
        migrations.AddField(
            model_name='pet',
            name='source',
            field=models.CharField(choices=[('PORTAL', 'Portal (Registered User)'), ('WALKIN', 'Walk-in (Guest)')], default='PORTAL', help_text='Whether this patient was registered via the portal or as a walk-in.', max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to=settings.AUTH_USER_MODEL),
        ),
    ]
