# Generated by Django 6.0 on 2026-03-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_pet_guest_owner_address_pet_guest_owner_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive pets will not show in appointment dropdowns but keep their medical history.', verbose_name='Active Status'),
        ),
    ]
