# Generated by Django 6.0 on 2026-03-14 02:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_pet_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['owner'], name='patients_pe_owner_i_722327_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['name'], name='patients_pe_name_24dce9_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['is_active'], name='patients_pe_is_acti_4a83e7_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['status'], name='patients_pe_status_408175_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['created_at'], name='patients_pe_created_12f3bf_idx'),
        ),
    ]
