# Generated by Django 6.0.3 on 2026-03-28 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_pet_patients_pe_owner_i_722327_idx_and_more'),
        ('settings', '0006_clinicalstatus_reasonforvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='clinical_status',
            field=models.ForeignKey(blank=True, help_text='Current clinical status of the pet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='settings.clinicalstatus'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(blank=True, choices=[('HEALTHY', 'Healthy'), ('MONITOR', 'Under Monitoring'), ('TREATMENT', 'In Treatment'), ('SURGERY', 'In Surgery'), ('DIAGNOSTICS', 'Pending Diagnostics'), ('CRITICAL', 'Critical')], default='HEALTHY', help_text='Legacy status field - use clinical_status instead', max_length=20),
        ),
    ]
