# Generated by Django 6.0.3 on 2026-04-04 12:19

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_pet_clinical_status_alter_pet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, help_text='Supported formats: .png, .jpeg (Max 10MB)', null=True, upload_to='pet_photos/', validators=[utils.validators.validate_image_file]),
        ),
    ]
