# Generated by Django 6.0.3 on 2026-04-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_alter_pet_photo'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pet',
            name='patients_pe_status_408175_idx',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='status',
        ),
    ]
