# Generated by Django 6.0.3 on 2026-04-18 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_remove_pet_patients_pe_status_408175_idx_and_more'),
        ('settings', '0012_legaldocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='patients.pet')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.clinicalstatus')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
