# Generated by Django 6.0.3 on 2026-05-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_clinicalstatuslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='source',
            field=models.CharField(choices=[('PORTAL', 'Portal Account'), ('WALKIN', 'Walk-In / Guest User')], default='PORTAL', help_text='Whether this patient was registered via the portal or as a walk-in.', max_length=10),
        ),
    ]
