# Generated by Django 6.0.3 on 2026-05-06 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_branch_is_main_source'),
        ('patients', '0017_alter_pet_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch where the pet belongs (used for filtering guest/walk-in users)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_pets', to='branches.branch'),
        ),
    ]
