# Generated by Django 6.0.3 on 2026-03-25 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_sync_staff_branches'),
        ('patients', '0012_pet_patients_pe_owner_i_722327_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_symptoms', models.TextField(blank=True, help_text='Symptoms provided for analysis')),
                ('input_history', models.TextField(blank=True, help_text='Medical history snapshot')),
                ('primary_condition', models.CharField(max_length=200)),
                ('primary_confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=10)),
                ('primary_reasoning', models.TextField(blank=True)),
                ('differential_diagnoses', models.JSONField(default=list, help_text='List of {condition, confidence, reasoning}')),
                ('recommended_tests', models.JSONField(default=list)),
                ('warning_signs', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_diagnoses', to='patients.pet')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_diagnoses', to='employees.staffmember')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_diagnoses', to='employees.staffmember')),
            ],
            options={
                'verbose_name': 'AI Diagnosis',
                'verbose_name_plural': 'AI Diagnoses',
                'ordering': ['-created_at'],
            },
        ),
    ]
