# Generated by Django 6.0.3 on 2026-03-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aidiagnosis',
            name='primary_confidence',
        ),
        migrations.AlterField(
            model_name='aidiagnosis',
            name='differential_diagnoses',
            field=models.JSONField(default=list, help_text='List of {condition, reasoning}'),
        ),
    ]
