# Generated by Django 6.0.3 on 2026-04-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0004_vet_in_the_loop_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidiagnosis',
            name='differential_diagnoses',
            field=models.JSONField(default=list, help_text='List of {condition, reasoning} for vet selection'),
        ),
        migrations.AlterField(
            model_name='aidiagnosis',
            name='input_history',
            field=models.TextField(blank=True, help_text='Medical history snapshot (last 10 entries)'),
        ),
        migrations.AlterField(
            model_name='aidiagnosis',
            name='input_symptoms',
            field=models.TextField(blank=True, help_text='Current symptoms provided for analysis'),
        ),
        migrations.AlterField(
            model_name='aidiagnosis',
            name='recommended_tests',
            field=models.JSONField(default=list, help_text='List of recommended tests for vet selection'),
        ),
    ]
