# Generated by Django 6.0.3 on 2026-04-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0005_alter_aidiagnosis_differential_diagnoses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidiagnosis',
            name='diagnosis_notes',
            field=models.TextField(blank=True, help_text='Extra details about the selected diagnosis (vet notes)'),
        ),
        migrations.AddField(
            model_name='aidiagnosis',
            name='test_notes',
            field=models.TextField(blank=True, help_text='Extra details about the selected tests (vet notes)'),
        ),
    ]
