# Generated by Django 6.0 on 2026-02-23 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_rename_address_line_1_branch_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('position', models.CharField(choices=[('VETERINARIAN', 'Veterinarian'), ('VET_ASSISTANT', 'Vet Assistant'), ('RECEPTIONIST', 'Receptionist'), ('ADMIN', 'Admin'), ('OJT', 'OJT')], max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_hired', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('license_number', models.CharField(blank=True, help_text='PRC license number (for vets)', max_length=100)),
                ('license_expiry', models.DateField(blank=True, help_text='License expiration date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='branches.branch')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='VetSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='branches.branch')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='employees.staffmember')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('staff', 'date', 'branch')},
            },
        ),
    ]
