# Generated by Django 5.2.7 on 2026-02-24 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_rename_address_line_1_branch_address_and_more'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vetschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vetschedule',
            name='shift_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('SURGERY', 'Surgery Only'), ('TELEHEALTH', 'Telehealth'), ('BREAK', 'Break'), ('CHECKUP', 'Check-up Only')], default='GENERAL', max_length=20),
        ),
        migrations.CreateModel(
            name='RecurringSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('shift_type', models.CharField(choices=[('GENERAL', 'General'), ('SURGERY', 'Surgery Only'), ('TELEHEALTH', 'Telehealth'), ('BREAK', 'Break'), ('CHECKUP', 'Check-up Only')], default='GENERAL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, help_text='Start applying from this date', null=True)),
                ('effective_until', models.DateField(blank=True, help_text='Stop applying after this date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_schedules', to='branches.branch')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_schedules', to='employees.staffmember')),
            ],
            options={
                'ordering': ['staff', 'day_of_week', 'start_time'],
            },
        ),
    ]
