# Generated by Django 6.0.3 on 2026-03-18 18:24

from django.db import migrations


def sync_staff_branches_forward(apps, schema_editor):
    """Sync StaffMember.branch from User.branch for all staff with linked User accounts."""
    StaffMember = apps.get_model('employees', 'StaffMember')

    # Get all staff members with linked user accounts
    staff_with_users = StaffMember.objects.filter(user__isnull=False).select_related('user')

    synced = 0
    for staff in staff_with_users:
        if staff.user and staff.user.branch:
            # Sync branch from User to StaffMember
            staff.branch = staff.user.branch
            staff.save(update_fields=['branch'])
            synced += 1

    print(f"Synced branch for {synced} staff members from their User accounts.")


def sync_staff_branches_reverse(apps, schema_editor):
    """Reverse migration - no action needed."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_staffmember_deleted_at_staffmember_is_deleted'),
    ]

    operations = [
        migrations.RunPython(sync_staff_branches_forward, sync_staff_branches_reverse),
    ]
