# Generated by Django 6.0.3 on 2026-03-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_branch_badge_label_branch_display_order_and_more'),
        ('employees', '0004_sync_staff_branches'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vetschedule',
            index=models.Index(fields=['branch', 'date'], name='employees_v_branch__375b92_idx'),
        ),
        migrations.AddIndex(
            model_name='vetschedule',
            index=models.Index(fields=['staff', 'date'], name='employees_v_staff_i_98f6af_idx'),
        ),
        migrations.AddIndex(
            model_name='vetschedule',
            index=models.Index(fields=['date', 'is_available'], name='employees_v_date_14c1cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='vetschedule',
            constraint=models.UniqueConstraint(fields=('staff', 'date', 'start_time', 'branch'), name='unique_vet_schedule_slot'),
        ),
    ]
