# Generated by Django 6.0.3 on 2026-04-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_vetschedule_employees_v_branch__375b92_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='default_days_worked',
            field=models.PositiveIntegerField(default=22, help_text='Default working days per month'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='default_other_allowance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default other allowances (transportation, meal, etc.)', max_digits=10),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='default_staff_allowance',
            field=models.DecimalField(decimal_places=2, default=2000, help_text='Default monthly staff allowance', max_digits=10),
        ),
    ]
