# Generated by Django 6.0.3 on 2026-05-02 20:03

import settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_staffmember_default_days_worked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringschedule',
            name='effective_from',
            field=models.DateField(blank=True, help_text='Start applying from this date (defaults to today if left blank)', null=True),
        ),
        migrations.AlterField(
            model_name='recurringschedule',
            name='effective_until',
            field=models.DateField(blank=True, help_text='Stop applying after this date (no limit if left blank)', null=True),
        ),
        migrations.AlterField(
            model_name='recurringschedule',
            name='shift_type',
            field=models.CharField(choices=settings.models.get_shift_type_choices, default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='vetschedule',
            name='shift_type',
            field=models.CharField(choices=settings.models.get_shift_type_choices, default='GENERAL', max_length=20),
        ),
    ]
