# Generated by Django 6.0.3 on 2026-07-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_recurringschedule_effective_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='default_custom_deductions',
            field=models.JSONField(blank=True, default=list, help_text='Default custom deductions copied into new payslips'),
        ),
    ]
