# Generated by Django 6.0.3 on 2026-08-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_staffmember_default_custom_deductions'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='biometric_id',
            field=models.CharField(blank=True, db_index=True, help_text='Scanner/biometric ID used to match attendance import files to the same staff member.', max_length=50, null=True, unique=True),
        ),
    ]
