# Generated by Django 6.0.3 on 2026-08-31 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_remove_staffmember_default_other_allowance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='default_staff_allowance',
            field=models.DecimalField(decimal_places=2, default=2000, help_text='Default staff allowance', max_digits=10),
        ),
    ]
