# Generated by Django 5.2.7 on 2026-03-01 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_rename_address_line_1_branch_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Product', 'Product'), ('Service', 'Service'), ('Medication', 'Medication')], default='Product', max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tax_rate', models.CharField(blank=True, max_length=50)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('track_stock', models.BooleanField(default=False)),
                ('initial_stock', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('duration', models.IntegerField(default=0, help_text='Duration in minutes')),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('content', models.TextField(blank=True, help_text='Manage content associated with this billable record.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billable_items', to='branches.branch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
