# Generated by Django 5.2.7 on 2026-03-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoiceitem_total_cost_invoiceitem_unit_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billableitem',
            name='type',
            field=models.CharField(choices=[('Product', 'Product'), ('Service', 'Service'), ('Medication', 'Medication')], default='Service', max_length=50),
        ),
    ]
