# Generated by Django 5.2.7 on 2026-03-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='billable_item',
        ),
        migrations.RemoveField(
            model_name='billableitem',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='billableitem',
            name='initial_stock',
        ),
        migrations.RemoveField(
            model_name='billableitem',
            name='inventory_product',
        ),
        migrations.RemoveField(
            model_name='billableitem',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='billableitem',
            name='reorder_level',
        ),
        migrations.RemoveField(
            model_name='billableitem',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='billableitem',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='billableitem',
            name='track_stock',
        ),
        migrations.RemoveField(
            model_name='billableitem',
            name='type',
        ),
        migrations.AlterField(
            model_name='billableitem',
            name='content',
            field=models.TextField(blank=True, help_text='Manage content associated with this service.'),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
