# Generated by Django 6.0 on 2026-03-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_remove_invoiceitem_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billableitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billableitem',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record should be treated as deleted.'),
        ),
    ]
