# Generated by Django 6.0 on 2026-03-15 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_rename_billableitem_to_service'),
        ('branches', '0004_branch_badge_label_branch_display_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='branches.branch'),
        ),
        migrations.CreateModel(
            name='CustomerStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('patient_name', models.CharField(help_text='Pet name', max_length=100)),
                ('owner_name', models.CharField(help_text='Pet owner name', max_length=200)),
                ('date', models.DateField(help_text='Statement date')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('treatment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('boarding', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vaccination', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('surgery', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('laboratory', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('grooming', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('others', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RELEASED', 'Released to Customer'), ('SENT', 'Sent via Email')], default='DRAFT', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_statements', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='Link to registered customer account', limit_choices_to={'role': 'PET_OWNER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Statement',
                'verbose_name_plural': 'Customer Statements',
                'ordering': ['-created_at'],
            },
        ),
    ]
