# Generated by Django 6.0 on 2026-03-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_service_branch_customerstatement'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerstatement',
            name='boarding_description',
            field=models.TextField(blank=True, help_text='Description of boarding services'),
        ),
        migrations.AddField(
            model_name='customerstatement',
            name='consultation_description',
            field=models.TextField(blank=True, help_text='Description of consultation services'),
        ),
        migrations.AddField(
            model_name='customerstatement',
            name='grooming_description',
            field=models.TextField(blank=True, help_text='Description of grooming services'),
        ),
        migrations.AddField(
            model_name='customerstatement',
            name='laboratory_description',
            field=models.TextField(blank=True, help_text='Description of laboratory services'),
        ),
        migrations.AddField(
            model_name='customerstatement',
            name='others_description',
            field=models.TextField(blank=True, help_text='Description of other services'),
        ),
        migrations.AddField(
            model_name='customerstatement',
            name='surgery_description',
            field=models.TextField(blank=True, help_text='Description of surgical services'),
        ),
        migrations.AddField(
            model_name='customerstatement',
            name='treatment_description',
            field=models.TextField(blank=True, help_text='Description of treatment services'),
        ),
        migrations.AddField(
            model_name='customerstatement',
            name='vaccination_description',
            field=models.TextField(blank=True, help_text='Description of vaccination services'),
        ),
    ]
