# Generated by Django 6.0.3 on 2026-04-10 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_customerstatement_sale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerstatement',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Link to registered customer account', limit_choices_to={'assigned_role__is_staff_role': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statements', to=settings.AUTH_USER_MODEL),
        ),
    ]
