# Generated by Django 6.0 on 2026-03-07 15:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0003_staffmember_deleted_at_staffmember_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code for this component (e.g., SSS, PHILHEALTH)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Display name', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('component_type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction')], default='EARNING', max_length=20)),
                ('is_percentage', models.BooleanField(default=False, help_text='If true, amount is treated as percentage of base salary')),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, help_text='Default amount or percentage value', max_digits=10)),
                ('is_taxable', models.BooleanField(default=True, help_text='Whether this component is subject to tax')),
                ('is_statutory', models.BooleanField(default=False, help_text='Whether this is a government-mandated deduction')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salary Component',
                'verbose_name_plural': 'Salary Components',
                'ordering': ['component_type', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., January 2026 Payroll', max_length=100)),
                ('month', models.PositiveIntegerField(help_text='Month number (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveIntegerField(help_text='Year (e.g., 2026)', validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, help_text='Total gross pay for this period', max_digits=14)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, help_text='Total deductions for this period', max_digits=14)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, help_text='Total net pay for this period', max_digits=14)),
                ('employee_count', models.PositiveIntegerField(default=0, help_text='Number of employees processed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payrolls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Period',
                'verbose_name_plural': 'Payroll Periods',
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PayrollTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, help_text='Employee base salary at time of processing', max_digits=12)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, help_text='Daily rate (base salary / working days)', max_digits=10)),
                ('days_worked', models.PositiveIntegerField(default=0, help_text='Number of days actually worked')),
                ('working_days', models.PositiveIntegerField(default=22, help_text='Standard working days in the period')),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, help_text='Total earnings before deductions', max_digits=12)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, help_text='Total additional earnings', max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, help_text='Total deductions', max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, help_text='Final take-home pay', max_digits=12)),
                ('earnings_breakdown', models.JSONField(blank=True, default=dict, help_text='Detailed breakdown of earnings')),
                ('deductions_breakdown', models.JSONField(blank=True, default=dict, help_text='Detailed breakdown of deductions')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_transactions', to='employees.staffmember')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payroll.payrollperiod')),
            ],
            options={
                'verbose_name': 'Payroll Transaction',
                'verbose_name_plural': 'Payroll Transactions',
                'ordering': ['-payroll_period__year', '-payroll_period__month', 'employee__last_name'],
                'unique_together': {('payroll_period', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Custom amount for this employee (leave blank to use component default)', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='employees.staffmember')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_structures', to='payroll.salarycomponent')),
            ],
            options={
                'verbose_name': 'Employee Salary Structure',
                'verbose_name_plural': 'Employee Salary Structures',
                'unique_together': {('employee', 'component')},
            },
        ),
    ]
