# Generated by Django 6.0 on 2026-03-07 15:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_staffmember_deleted_at_staffmember_is_deleted'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeesalarystructure',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='employeesalarystructure',
            name='component',
        ),
        migrations.RemoveField(
            model_name='employeesalarystructure',
            name='employee',
        ),
        migrations.AlterUniqueTogether(
            name='payrolltransaction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='payrolltransaction',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='payrolltransaction',
            name='payroll_period',
        ),
        migrations.AlterModelOptions(
            name='payrollperiod',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.RenameField(
            model_name='payrollperiod',
            old_name='processed_date',
            new_name='generated_at',
        ),
        migrations.RemoveField(
            model_name='payrollperiod',
            name='name',
        ),
        migrations.RemoveField(
            model_name='payrollperiod',
            name='processed_by',
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_payrolls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='employee_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='month',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('RELEASED', 'Released')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='total_gross',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='total_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, help_text='Monthly base salary', max_digits=12)),
                ('days_worked', models.PositiveIntegerField(default=0)),
                ('days_absent', models.PositiveIntegerField(default=0)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('holiday_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('allowance', models.DecimalField(decimal_places=2, default=0, help_text='Other allowances (transportation, meal, etc.)', max_digits=10)),
                ('sss', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('philhealth', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pagibig', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cash_advance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('late_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('absent_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('RELEASED', 'Released')], default='DRAFT', max_length=20)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('received_by_employee', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='employees.staffmember')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollperiod')),
            ],
            options={
                'ordering': ['employee__last_name', 'employee__first_name'],
                'unique_together': {('payroll_period', 'employee')},
            },
        ),
        migrations.DeleteModel(
            name='SalaryComponent',
        ),
        migrations.DeleteModel(
            name='EmployeeSalaryStructure',
        ),
        migrations.DeleteModel(
            name='PayrollTransaction',
        ),
    ]
