# Generated by Django 6.0 on 2026-03-08 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_staffmember_deleted_at_staffmember_is_deleted'),
        ('payroll', '0002_alter_employeesalarystructure_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('PERIOD_CREATED', 'Period Created'), ('PERIOD_GENERATED', 'Payslips Generated'), ('PERIOD_RELEASED', 'Payroll Released'), ('PERIOD_DELETED', 'Period Deleted'), ('PAYSLIP_CREATED', 'Payslip Created'), ('PAYSLIP_EDITED', 'Payslip Edited'), ('PAYSLIP_APPROVED', 'Payslip Approved'), ('PAYSLIP_SENT', 'Payslip Sent'), ('VET_SALARY_UPDATED', 'Vet Salary Updated'), ('VET_BONUS_ADDED', 'Bonus Added'), ('VET_DEDUCTION_ADDED', 'Deduction Added'), ('SYSTEM_LOGIN', 'Admin Login'), ('SYSTEM_EXPORT', 'Data Exported')], max_length=30)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='payroll.payrollperiod')),
                ('payslip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='payroll.payslip')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_audit_logs', to='employees.staffmember')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Audit Log',
                'verbose_name_plural': 'Payroll Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
