# Generated by Django 6.0 on 2026-03-09 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_staffmember_deleted_at_staffmember_is_deleted'),
        ('payroll', '0003_payrollauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(choices=[('REGULAR', 'Regular (1.25x)'), ('HOLIDAY', 'Holiday (1.30x)'), ('SPECIAL', 'Special Holiday (1.50x)')], max_length=20, unique=True)),
                ('multiplier', models.DecimalField(decimal_places=2, help_text='Multiplier (e.g., 1.25 for 25% extra)', max_digits=3)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['rate_type'],
            },
        ),
        migrations.CreateModel(
            name='StatutoryDeductionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_type', models.CharField(choices=[('SSS', 'SSS'), ('PHILHEALTH', 'PhilHealth'), ('PAGIBIG', 'PAG-IBIG'), ('TAX', 'Income Tax')], max_length=20)),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('employee_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('employer_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('effective_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Statutory Deduction Table',
                'verbose_name_plural': 'Statutory Deduction Tables',
                'ordering': ['deduction_type', 'min_salary'],
            },
        ),
        migrations.AddField(
            model_name='payslip',
            name='thirteenth_month_pay',
            field=models.DecimalField(decimal_places=2, default=0, help_text='13th month pay (Philippine labor requirement)', max_digits=10),
        ),
        migrations.CreateModel(
            name='CashAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('RELEASED', 'Released'), ('DEDUCTED', 'Deducted')], default='PENDING', max_length=20)),
                ('reason', models.TextField()),
                ('requested_date', models.DateField(auto_now_add=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('released_date', models.DateField(blank=True, null=True)),
                ('deducted_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('deduct_from_payroll_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_advance_deductions', to='payroll.payrollperiod')),
                ('deducted_payslip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_cash_advances', to='payroll.payslip')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_advances', to='employees.staffmember')),
            ],
            options={
                'ordering': ['-requested_date'],
            },
        ),
        migrations.CreateModel(
            name='PayslipEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced')], default='SENT', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='payroll.payslip')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
