# Generated by Django 6.0 on 2026-03-09 08:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_overtimerate_statutorydeductiontable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashadvance',
            options={'ordering': ['-requested_at']},
        ),
        migrations.RemoveField(
            model_name='cashadvance',
            name='approved_date',
        ),
        migrations.RemoveField(
            model_name='cashadvance',
            name='deducted_date',
        ),
        migrations.RemoveField(
            model_name='cashadvance',
            name='released_date',
        ),
        migrations.RemoveField(
            model_name='cashadvance',
            name='requested_date',
        ),
        migrations.AddField(
            model_name='cashadvance',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashadvance',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cash_advances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashadvance',
            name='deducted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashadvance',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cashadvance',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_cash_advances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cashadvance',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DEDUCTED', 'Deducted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
