# Generated by Django 6.0 on 2026-03-14 02:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_staffmember_deleted_at_staffmember_is_deleted'),
        ('payroll', '0007_fix_overflow_decimals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['year', 'month'], name='payroll_pay_year_149b61_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['status'], name='payroll_pay_status_c18070_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['status'], name='payroll_pay_status_409e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['payroll_period', 'status'], name='payroll_pay_payroll_a648a4_idx'),
        ),
    ]
