# Generated by Django 6.0 on 2026-03-16 08:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_payrollperiod_payroll_pay_year_149b61_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='clinic_pagibig',
            field=models.DecimalField(decimal_places=2, default=0, help_text='PAG-IBIG contribution paid by the clinic', max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='clinic_philhealth',
            field=models.DecimalField(decimal_places=2, default=0, help_text='PhilHealth contribution paid by the clinic', max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='clinic_sss',
            field=models.DecimalField(decimal_places=2, default=0, help_text='SSS contribution paid by the clinic', max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='staff_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('2000'), help_text='Monthly staff allowance (split ₱1,000 on 15th + ₱1,000 on 30th)', max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='total_clinic_contributions',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total clinic-paid benefits (SSS + PhilHealth + PAG-IBIG)', max_digits=12),
        ),
    ]
