# Generated by Django 6.0.3 on 2026-03-23 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_payslip_clinic_pagibig_payslip_clinic_philhealth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashadvance',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='cashadvance',
            name='deduct_from_payroll_period',
        ),
        migrations.RemoveField(
            model_name='cashadvance',
            name='deducted_payslip',
        ),
        migrations.RemoveField(
            model_name='cashadvance',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='cashadvance',
            name='requested_by',
        ),
        migrations.DeleteModel(
            name='OvertimeRate',
        ),
        migrations.DeleteModel(
            name='CashAdvance',
        ),
    ]
