# Generated by Django 6.0.3 on 2026-04-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_remove_cash_advance_and_overtime_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollauditlog',
            name='action_type',
            field=models.CharField(choices=[('PERIOD_CREATED', 'Period Created'), ('PERIOD_GENERATED', 'Payslips Generated'), ('PERIOD_RELEASED', 'Payroll Released'), ('PERIOD_DELETED', 'Period Deleted'), ('PAYSLIP_CREATED', 'Payslip Created'), ('PAYSLIP_EDITED', 'Payslip Edited'), ('PAYSLIP_APPROVED', 'Payslip Approved'), ('PAYSLIP_SENT', 'Payslip Sent'), ('PAYSLIP_DELETED', 'Payslip Deleted'), ('VET_SALARY_UPDATED', 'Vet Salary Updated'), ('VET_BONUS_ADDED', 'Bonus Added'), ('VET_DEDUCTION_ADDED', 'Deduction Added'), ('SYSTEM_LOGIN', 'Admin Login'), ('SYSTEM_EXPORT', 'Data Exported')], max_length=30),
        ),
    ]
