# Generated by Django 6.0.3 on 2026-07-10 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_alter_payrollauditlog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='custom_deductions_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total of custom line-item deductions attached to the payslip', max_digits=12),
        ),
        migrations.CreateModel(
            name='PayslipDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_deductions', to='payroll.payslip')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
