# Generated by Django 6.0.3 on 2026-08-29 04:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_merge_semi_monthly_and_remove_allowance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollperiod',
            options={'ordering': ['-year', '-month', '-period_type']},
        ),
        migrations.RenameIndex(
            model_name='payrollperiod',
            new_name='payroll_pay_period__64d4a3_idx',
            old_name='payroll_pay_period_idx',
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='employee_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of employees processed in this period'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total deductions for this period', max_digits=14),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='total_gross',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total gross pay for this period', max_digits=14),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='total_net',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total net pay for this period', max_digits=14),
        ),
    ]
