# Generated by Django 6.0.3 on 2026-08-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0017_alter_payrollperiod_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='excess_leave_days',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total leave days exceeding the 4 mandatory rest days (only regular leave counted for deduction)', max_digits=5),
        ),
        migrations.AddField(
            model_name='payslip',
            name='regular_leave_days',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Regular leave days exceeding rest day allowance (UNPAID - deducted from salary)', max_digits=5),
        ),
        migrations.AddField(
            model_name='payslip',
            name='rest_days_actual',
            field=models.PositiveIntegerField(default=0, help_text='Actual rest days from attendance data'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='rest_days_exceeded_deduction',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount deducted due to exceeding 4 mandatory rest days (applies to appropriate period half)', max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='rest_days_mandatory',
            field=models.PositiveIntegerField(default=4, help_text='Mandatory rest days per month (client requirement: minimum 4)'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='sick_leave_days',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sick leave days (PAID - not deducted from salary)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='period_type',
            field=models.CharField(choices=[('MONTHLY', 'Full Month'), ('SEMI_FIRST', 'First Half'), ('SEMI_SECOND', 'Second Half')], default='MONTHLY', help_text='Select full month, first half (1-15), or second half (16-EOMonth)', max_length=20),
        ),
    ]
