# Generated by Django 6.0.3 on 2026-08-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0018_add_leave_and_rest_days_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='paid_leave_days',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Paid leave days used; this reduces the absences count before deduction', max_digits=5),
        ),
        migrations.AddField(
            model_name='payslip',
            name='paid_leave_type',
            field=models.CharField(blank=True, default='Sick Leave', help_text='Paid leave category for the current payslip', max_length=50),
        ),
    ]
