# Generated by Django 6.0.3 on 2026-08-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0019_payslip_paid_leave_days_payslip_paid_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollperiod',
            name='period_type',
            field=models.CharField(choices=[('SEMI_FIRST', 'First Half'), ('SEMI_SECOND', 'Second Half')], default='SEMI_FIRST', help_text='Select the first half (1-15) or second half (16-EOMonth)', max_length=20),
        ),
    ]
