# Generated by Django 6.0.3 on 2026-09-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0021_payslipemaillog_unique_successful'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payslipemaillog',
            name='unique_successful_payslip_email',
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='period_type',
            field=models.CharField(choices=[('MONTHLY', 'Full Month'), ('SEMI_FIRST', 'First Half'), ('SEMI_SECOND', 'Second Half')], default='MONTHLY', help_text='Select full month, first half (1-15), or second half (16-EOMonth)', max_length=20),
        ),
    ]
