# Generated by Django 6.0.3 on 2026-09-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0022_remove_payslipemaillog_unique_successful_payslip_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollperiod',
            name='period_type',
            field=models.CharField(choices=[('MONTHLY', 'Full Month'), ('SEMI_FIRST', 'First Half'), ('SEMI_SECOND', 'Second Half')], default='SEMI_FIRST', help_text='Select full month, first half (1-15), or second half (16-EOMonth)', max_length=20),
        ),
    ]
