# Generated by Django 6.0.3 on 2026-09-09 12:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0024_alter_payrollperiod_period_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='staff_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('2000'), help_text='Staff allowance for this half-month payroll period', max_digits=10),
        ),
    ]
