# Generated by Django 6.0 on 2026-03-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_rename_address_line_1_branch_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='clinic_license_number',
            field=models.CharField(blank=True, help_text='Clinic/branch registration or license number', max_length=100),
        ),
    ]
