# Generated by Django 6.0 on 2026-03-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_dob_to_date_field_and_clinic_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='badge_label',
            field=models.CharField(blank=True, help_text="Display badge (e.g., 'Main Branch', 'New!')", max_length=50),
        ),
        migrations.AddField(
            model_name='branch',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order for contact page display (lower = first)'),
        ),
        migrations.AddField(
            model_name='branch',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook page URL', max_length=500),
        ),
        migrations.AddField(
            model_name='branch',
            name='google_maps_embed_url',
            field=models.URLField(blank=True, help_text='Google Maps embed URL for iframe display', max_length=1000),
        ),
        migrations.AddField(
            model_name='branch',
            name='google_maps_link',
            field=models.URLField(blank=True, help_text='Direct link to Google Maps location', max_length=500),
        ),
        migrations.AddField(
            model_name='branch',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL', max_length=500),
        ),
        migrations.AddField(
            model_name='branch',
            name='messenger_url',
            field=models.URLField(blank=True, help_text='Facebook Messenger URL', max_length=500),
        ),
        migrations.AddField(
            model_name='branch',
            name='tiktok_url',
            field=models.URLField(blank=True, help_text='TikTok profile URL', max_length=500),
        ),
    ]
