# Generated by Django 6.0.3 on 2026-04-26 17:21

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_branch_badge_label_branch_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='logo',
            field=models.ImageField(blank=True, help_text='Supported formats: .png, .jpeg (Max 10MB)', null=True, upload_to='clinic/branches/', validators=[utils.validators.validate_image_file]),
        ),
    ]
