# Generated by Django 6.0.3 on 2026-05-03

from django.db import migrations, models


def mark_pilar_as_main_source(apps, schema_editor):
    Branch = apps.get_model('branches', 'Branch')
    Branch.objects.filter(name='FMH Animal Clinic - Pilar').update(is_main_source=True)


def unmark_pilar_as_main_source(apps, schema_editor):
    Branch = apps.get_model('branches', 'Branch')
    Branch.objects.filter(name='FMH Animal Clinic - Pilar').update(is_main_source=False)


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_branch_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_main_source',
            field=models.BooleanField(default=False, help_text='Marks the branch that supplies stock to satellite branches.'),
        ),
        migrations.RunPython(mark_pilar_as_main_source, unmark_pilar_as_main_source),
    ]