# Generated by Django 6.0.3 on 2026-04-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='cash_drawer',
        ),
        migrations.DeleteModel(
            name='CashDrawer',
        ),
    ]
