# Generated by Django 6.0.3 on 2026-04-04 12:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_remove_sale_cash_drawer_delete_cashdrawer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='discount_amount',
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount as a percentage (0-100)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount_reason',
            field=models.CharField(blank=True, help_text='Required when discount is applied', max_length=200),
        ),
    ]
