# Generated by Django 6.0.3 on 2026-04-04 12:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_remove_sale_discount_amount_sale_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount as a percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
