# Generated by Django 6.0.3 on 2026-04-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_alter_sale_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='soa_data',
            field=models.TextField(blank=True, help_text='JSON data for custom SOA overrides'),
        ),
    ]
