# Generated by Django 6.0.3 on 2026-04-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_sale_soa_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='guest_pet_name',
            field=models.CharField(blank=True, help_text='Pet name for walk-in customers', max_length=200),
        ),
    ]
